Repository openshift/cluster-network-operator, pull requests merged in 2018-11, with the labels that each got.

#27 manifests: change to using installer-created apiserver environment.
  manifests/0000_07_cluster-network-operator_03_daemonset.yaml
Labels: approved, lgtm, size/S

#29 openshift-sdn: Add stupid loop to wait out crio SELinux relabeling.
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/M

#31 openshift-sdn: remove sdn relabel wait, remove runAsUser
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/M

#33 openshift-sdn: ovs daemonset improvements:
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, lgtm, size/S

#34 update owners file
  OWNERS
Labels: approved, lgtm, size/XS

#37 openshift-sdn: use the crio CRI socket
  pkg/network/openshift_sdn.go
Labels: approved, lgtm, size/XS

#38 Remove ip_forward sysctl
  bindata/network/openshift-sdn/sdn.yaml
  cmd/cluster-network-operator/main.go
  sample-config.yaml
Labels: approved, lgtm, size/S

#41 Block unsafe changes
  cmd/cluster-network-renderer/main.go
  pkg/apis/networkoperator/v1/networkconfig_types.go
  pkg/controller/networkconfig/networkconfig_controller.go
  pkg/controller/networkconfig/previous.go
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/render.go
  pkg/network/render_test.go
Labels: approved, lgtm, size/L

#43 remove kubelet pki from sdn pod
  bindata/network/openshift-sdn/sdn.yaml
  pkg/network/openshift_sdn.go
Labels: approved, lgtm, size/S
