Repository openshift/cluster-network-operator, pull requests merged in 2019-08, with the labels that each got.

#237 Condense CNI reference plugins images into a single image
  bindata/network/multus/003-dhcp-daemon.yaml
  bindata/network/multus/multus.yaml
  manifests/0000_70_cluster-network-operator_03_daemonset.yaml
  manifests/image-references
  pkg/network/multus.go
Labels: approved, lgtm, size/M

#270 kuryr: get CNI loopback plugin from CNIPluginsImage
  bindata/network/kuryr/004-daemon.yaml
  pkg/network/kuryr.go
Labels: approved, lgtm, size/XS

#273 add the api group to the override spec
  hack/overrides-patch.yaml
Labels: approved, lgtm, size/XS

#272 Don't require clusterNetwork and serviceNetwork to be set in operator type
  manifests/0000_70_cluster-network-operator_01_crd.yaml
Labels: approved, lgtm, size/XS

#245 Adds Proxy Controller
  Gopkg.lock
  pkg/controller/add_networkconfig.go
  pkg/controller/proxyconfig/controller.go
  pkg/controller/proxyconfig/status.go
  pkg/controller/proxyconfig/validation.go
  pkg/controller/statusmanager/status_manager.go
  pkg/names/names.go
  pkg/network/kube_proxy.go
  pkg/network/kube_proxy_test.go
  pkg/util/validation/network.go
Labels: approved, lgtm, size/L

#284 Moves noProxy merge func to a separate pkg
  pkg/controller/proxyconfig/status.go
  pkg/util/proxyconfig/merge.go
Labels: approved, lgtm, size/L

#280 Fixes proxy validation error formatting
  pkg/controller/proxyconfig/validation.go
Labels: approved, lgtm, size/XS

#286 Fixes Bug 1740027: Checks length of values in noProxy merge
  pkg/util/proxyconfig/merge.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#277 Adds readinessEndpoint validation for Proxy API type.
  pkg/controller/proxyconfig/controller.go
  pkg/controller/proxyconfig/validation.go
Labels: approved, lgtm, size/M

#287 modify default failureThreshold for kuryr components
  bindata/network/kuryr/004-daemon.yaml
  bindata/network/kuryr/005-controller.yaml
Labels: approved, lgtm, size/XS

#274 Add CA bundle injector
  Gopkg.lock
  pkg/controller/add_networkconfig.go
  pkg/controller/configmap_ca_injector/controller.go
  pkg/names/names.go
  pkg/util/validation/trustbundle.go
Labels: approved, lgtm, size/L

#271 Adds Trust Bundle Publishing to Proxy Controller
  pkg/controller/proxyconfig/controller.go
  pkg/controller/proxyconfig/validation.go
  pkg/names/names.go
Labels: approved, lgtm, size/L

#288 openshift-sdn: get CNI loopback and host-local plugins from CNIPluginsImage
  bindata/network/openshift-sdn/sdn.yaml
  pkg/network/openshift_sdn.go
Labels: approved, lgtm, size/S

#291 Bug 1735538: Adding cni-version to multus daemonset yaml
  bindata/network/multus/multus.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#292 manifests: the openshift-sdn type isn't actually required
  manifests/0000_70_cluster-network-operator_01_crd.yaml
Labels: approved, lgtm, size/XS

#294 run-locally.sh: fix -m without -n
  hack/run-locally.sh
Labels: approved, lgtm, size/XS

#275 Bug 1743302: Kuryr: Expand svc net to fix VRRP ports conflicts
  Gopkg.lock
  manifests/0000_70_cluster-network-operator_01_crd.yaml
  pkg/network/kuryr.go
  pkg/network/kuryr_test.go
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/util/ip/addr.go
  pkg/util/ip/addr_test.go
  vendor/github.com/openshift/api/apps/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/doc.go
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/oauth/v1/generated.pb.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/generated.pb.go
  vendor/github.com/openshift/api/quota/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/template/v1/generated.pb.go
  vendor/github.com/openshift/api/user/v1/generated.pb.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#295 Adds .svc and .svc.cluster.local to default noProxy
  pkg/util/proxyconfig/merge.go
Labels: approved, lgtm, size/XS

#298 OpenStack: Adjust kuryr default configuration
  bindata/network/kuryr/003-config.yaml
  bindata/network/kuryr/005-controller.yaml
  pkg/network/kuryr.go
  pkg/network/kuryr_test.go
Labels: approved, lgtm, size/S

#289 Adds proxy https readinessEndpoints support
  pkg/controller/proxyconfig/controller.go
  pkg/controller/proxyconfig/validation.go
  pkg/util/validation/trustbundle.go
Labels: approved, lgtm, size/L

#278 Add Kuryr DNS modifications webhook
  bindata/network/kuryr/006-service.yaml
  bindata/network/kuryr/007-admission.secret.yaml
  bindata/network/kuryr/008-webhook.secret.yaml
  bindata/network/kuryr/009-admission-controller.yaml
  bindata/network/kuryr/010-webhook.yaml
  pkg/bootstrap/types.go
  pkg/names/names.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/util/cert/cert.go
Labels: approved, lgtm, size/L

#279 Bug 1737026: Making set internal to the statusManager and adding mutex for thread safety
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/proxyconfig/controller.go
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#301 Set version on network cluster operator with kuryr SDN
  bindata/network/kuryr/004-daemon.yaml
  bindata/network/kuryr/005-controller.yaml
  bindata/network/kuryr/009-admission-controller.yaml
  pkg/network/kuryr.go
Labels: approved, lgtm, size/XS

#293 Bug 1743587: Adding cni-version to multus daemonset yaml
  bindata/network/multus/multus.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#302 Bug 1746360: openshift-sdn: allow empty mode
  pkg/network/openshift_sdn.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#304 Adds mergeProxy() tests and node subdomain to default noProxy list
  pkg/util/proxyconfig/no_proxy.go
  pkg/util/proxyconfig/no_proxy_test.go
Labels: approved, lgtm, size/L

#300 Adding status to configmap ca injector controller
  pkg/controller/configmap_ca_injector/controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: approved, lgtm, size/S
