Repository openshift/cluster-network-operator, pull requests merged in 2019-09, with the labels that each got.

#305 Bug 1744532: Adds machineCIDR noProxy support for all platforms
  pkg/util/proxyconfig/no_proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#307 Bug 1748354: Kuryr: Add external_svc_net to kuryr.conf
  bindata/network/kuryr/003-config.yaml
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#308 Kuryr: Open just 6443 on masters SG
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, lgtm, size/XS

#299 Alternate configuration directory + 00-multus.conf regeneration
  bindata/network/kuryr/004-daemon.yaml
  bindata/network/multus/multus.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/kuryr.go
  pkg/network/kuryr_test.go
  pkg/network/multus.go
  pkg/network/openshift_sdn.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render.go
Labels: approved, lgtm, size/L

#303 Bug 1737026: Use retry mechanism for fixing updates on stale objects in cache
  pkg/controller/statusmanager/status_manager.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#309 Kuryr: Set region_name in kuryr.conf
  bindata/network/kuryr/003-config.yaml
Labels: approved, lgtm, size/XS

#310 Bug 1749446: Revert "Merge pull request #299 from dougbtv/alternate-config-dir"
  bindata/network/kuryr/004-daemon.yaml
  bindata/network/multus/multus.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/kuryr.go
  pkg/network/kuryr_test.go
  pkg/network/multus.go
  pkg/network/openshift_sdn.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#312 Bug 1750991: Fixes http readinessEndpoint validation for httpsProxy
  pkg/controller/proxyconfig/validation.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#314 Bug 1751070: Updates SimpleMacvlan to add AdditionalNetworkNamespace to template data
  pkg/network/additional_networks.go
  pkg/network/additional_networks_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#315 Bug 1752371: Kuryr: Open etcd traffic from svc subnet to master nodes
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#316 Bug 1752905: Kuryr: Allow usage of SCC's to allow pod update
  bindata/network/kuryr/001-rbac.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#313 Bug 1748162: Shift ovn db ports to 9000-9999 range
  bindata/network/ovn-kubernetes/005-service.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#319 Bug 1753014: Kuryr: Fix kuryr bootstrap when lbaas API has ERROR status
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#311 Bug 1732598: Alternate CNI config dir
  bindata/network/kuryr/004-daemon.yaml
  bindata/network/multus/multus.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/kuryr.go
  pkg/network/kuryr_test.go
  pkg/network/multus.go
  pkg/network/openshift_sdn.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#233 Bug 1751756: Kuryr: Add health monitor to Octavia load balancer
  Gopkg.lock
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#325 Fixes Bug 1754049: Adds GCP metadata hostnames to default noProxy
  pkg/controller/proxyconfig/validation.go
  pkg/util/proxyconfig/no_proxy.go
  pkg/util/proxyconfig/no_proxy_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
