Repository openshift/cluster-network-operator, pull requests merged in 2019-06, with the labels that each got.

#184 hack: ensure 'aws' command output is JSON
  hack/open-ovn-ports.sh
Labels: approved, lgtm, size/XS

#182 Render the default ClusterNetwork
  bindata/network/openshift-sdn/005-clusternetwork.yaml
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/testutil_test.go
Labels: approved, lgtm, size/M

#185 Remove (unused) ovn-kube health check ports, which conflict with kube-controller-manager
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, size/M

#176 manifests: change image references to 4.2
  manifests/0000_70_cluster-network-operator_03_daemonset.yaml
  manifests/image-references
Labels: approved, lgtm, size/M

#187 Update sdn-controller RBAC
  bindata/network/openshift-sdn/003-rbac-controller.yaml
Labels: approved, lgtm, size/M

#190 Add readinessProbe to ovn-kubernetes
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, size/XS

#188 Revert "Merge pull request #183 from wking/revert-OVS-shutdown-change"
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, lgtm, size/S

#192 update kubelet label to use upstream GA label
  bindata/network/additional-networks/sriov/sriov-cni.yaml
  bindata/network/additional-networks/sriov/sriov-device-plugin.yaml
  bindata/network/multus/003-dhcp-daemon.yaml
  bindata/network/multus/multus.yaml
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/000-ns.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, size/S

#193 Use the go-native flag for verbosity
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/XS

#191 Further SDN config updates
  Gopkg.lock
  bindata/network/openshift-sdn/001-crd.yaml
  bindata/network/openshift-sdn/controller.yaml
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/consts.go
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/consts.go
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/register.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/unidling/v1alpha1/types.go
Labels: approved, lgtm, size/XL

#197 Mount host / into ovnkube-node container, for iptables binaries
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, size/S

#186 run-locally.sh: add from-scratch cluster up capability
  HACKING.md
  hack/run-locally.sh
Labels: approved, lgtm, size/L

#203 Slightly improve Progressing statuses
  pkg/controller/statusmanager/status_manager.go
Labels: approved, lgtm, size/XS

#202 Allow running open-ovn-ports.sh multiple times
  hack/open-ovn-ports.sh
Labels: approved, lgtm, size/XS

#204 run-locally.sh: fix name of openshift-install binary in test
  hack/run-locally.sh
Labels: approved, lgtm, size/XS

#195 Render a kube-proxy config YAML file
  Gopkg.lock
  Gopkg.toml
  bindata/network/openshift-sdn/sdn.yaml
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/proxy.go
  pkg/network/proxy_test.go
  pkg/util/k8s/kubeproxy.go
  pkg/util/k8s/kubeproxy_test.go
  vendor/k8s.io/kube-proxy/LICENSE
  vendor/k8s.io/kube-proxy/config/v1alpha1/doc.go
  vendor/k8s.io/kube-proxy/config/v1alpha1/register.go
  vendor/k8s.io/kube-proxy/config/v1alpha1/types.go
  vendor/k8s.io/kube-proxy/config/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#189 adding alerts for sdn in prometheus
  bindata/network/openshift-sdn/alert-rules.yaml
Labels: approved, lgtm, size/M

#201 Install standalone kube-proxy.
  bindata/kube-proxy/000-ns.yaml
  bindata/kube-proxy/001-rbac.yaml
  bindata/kube-proxy/kube-proxy.yaml
  bindata/kube-proxy/monitor.yaml
  manifests/0000_70_cluster-network-operator_03_daemonset.yaml
  manifests/image-references
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/proxy.go
  pkg/network/proxy_test.go
  pkg/network/render.go
Labels: approved, lgtm, size/XL

#205 Actually pass --proxy-config to openshift-sdn
  bindata/network/openshift-sdn/sdn.yaml
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
Labels: approved, lgtm, size/L

#209 change the serverity level for alert NetworkPodsCrashLooping
  bindata/network/openshift-sdn/alert-rules.yaml
Labels: approved, lgtm, size/XS

#210 Make Kuryr pods labels unambiguous
  bindata/network/kuryr/004-daemon.yaml
  bindata/network/kuryr/005-controller.yaml
Labels: approved, lgtm, size/S

#196 verify-style: run dep check
  .gitignore
  Gopkg.lock
  hack/update-codegen.sh
  hack/verify-codegen.sh
  hack/verify-style.sh
  vendor/github.com/gogo/protobuf/test/tags/doc.go
  vendor/github.com/gogo/protobuf/test/tags/tags.pb.go
Labels: approved, lgtm, size/L

#206 remove all sriov bits from CNO
  bindata/network/additional-networks/sriov/000-ns.yaml
  bindata/network/additional-networks/sriov/002-rbac.yaml
  bindata/network/additional-networks/sriov/network-attachment.yaml
  bindata/network/additional-networks/sriov/sriov-cni.yaml
  bindata/network/additional-networks/sriov/sriov-device-plugin.yaml
  manifests/0000_70_cluster-network-operator_03_daemonset.yaml
  manifests/image-references
  pkg/network/additional_networks_test.go
  pkg/network/render.go
  pkg/network/sriov.go
Labels: approved, lgtm, size/L

#212 sdn-ovs: allow ovs daemons to run as non-root
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, lgtm

#213 Add validations and additional printer columns to Kuryr CRDs
  bindata/network/kuryr/002-crds.yaml
Labels: approved, lgtm, size/L
