Repository openshift/cluster-network-operator, pull requests merged in 2019-04, with the labels that each got.

#137 Remove /etc/cni/net.d/ file when plugin is down
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, size/S

#138 sriov: report release version number of daemonsets
  bindata/network/additional-networks/sriov/sriov-cni.yaml
  bindata/network/additional-networks/sriov/sriov-device-plugin.yaml
  pkg/network/sriov.go
Labels: approved, lgtm, size/XS

#139 Pass the "real" apiserver info to the multus setup script
  bindata/network/multus/multus.yaml
  pkg/network/multus.go
Labels: approved, lgtm, size/XS

#136 Call syncFailing on SetNotFailing method
  pkg/controller/statusmanager/status_manager.go
Labels: approved, lgtm, size/XS

#140 improvements to run-locally.sh
  INSTALLER-HACKING.md
  hack/run-locally.sh
Labels: approved, lgtm, size/L

#141 Pipe socat stdout and stderr to dev null
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/XS

#143 status: catch a few more Progressing cases
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
Labels: approved, lgtm, size/M

#142 Bug 1666223 - Remove temporary hack around vxlanPort serialization
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
Labels: approved, lgtm, size/S

#145 sdn: update kube-proxy metrics flags for 1.13
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
Labels: approved, lgtm, size/S

#149 Be less pessimistic about operator status at startup
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
Labels: approved, lgtm, size/L

#153 Fix handling of Deployment Progressing status
  pkg/controller/statusmanager/status_manager.go
Labels: approved, lgtm, size/XS

#151 openshift-sdn: configure sdn readiness probe
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/XS

#154 Add helper script to open OVN ports on AWS
  hack/open-ovn-ports.sh
Labels: approved, lgtm, size/M

#157 Add node-selector annotation to namespace
  bindata/network/openshift-sdn/003-rbac-controller.yaml
  manifests/0000_07_cluster-network-operator_00_namespace.yaml
Labels: size/XS

#116 openshift-sdn: mount full sysconfig directory
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/S

#152 additional-networks: add Namespace support
  Gopkg.lock
  bindata/network/additional-networks/raw/network-attachment.yaml
  bindata/network/additional-networks/sriov/network-attachment.yaml
  manifests/0000_07_cluster-network-operator_01_crd.yaml
  pkg/network/additional_networks.go
  pkg/network/additional_networks_test.go
  pkg/network/sriov.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/types.go
Labels: approved, lgtm, size/L

#156 Use non-deprecated crio URL format
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
Labels: approved, lgtm, size/XS

#159 openshift-sdn: add kube-proxy liveness probe
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/XS

#158 Move component to an appropriate upgrade order (network)
  manifests/0000_70_cluster-network-operator_00_namespace.yaml
  manifests/0000_70_cluster-network-operator_01_crd.yaml
  manifests/0000_70_cluster-network-operator_02_rbac.yaml
  manifests/0000_70_cluster-network-operator_03_daemonset.yaml
  manifests/0000_70_cluster-network-operator_04_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#161 openshift-sdn: log ovs and sdn to the system journal
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/S

#162 Revert "openshift-sdn: log ovs and sdn to the system journal"
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/openshift-sdn/sdn.yaml
Labels: size/S
