Repository openshift/cluster-network-operator, pull requests merged in 2019-03, with the labels that each got.

#111 Some small operator fixes
  hack/verify-style.sh
  pkg/network/cluster_config.go
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/util/clusteroperator/status_manager.go
  pkg/util/clusteroperator/status_manager_test.go
  sample-config.yaml
Labels: approved, lgtm, size/L

#112 manifests: ensure system priorities
  bindata/network/multus/multus.yaml
  bindata/network/openshift-sdn/controller.yaml
  manifests/0000_07_cluster-network-operator_03_daemonset.yaml
Labels: approved, lgtm, size/XS

#114 Fix build on non-Linux by not trying to guess the default MTU
  pkg/network/mtu.go
  pkg/network/mtu_unsupported.go
Labels: approved, lgtm, size/XS

#110 Report version number from payload "when we hit level"
  bindata/network/multus/multus.yaml
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/openshift-sdn/sdn.yaml
  manifests/0000_07_cluster-network-operator_03_daemonset.yaml
  manifests/0000_07_cluster-network-operator_04_clusteroperator.yaml
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/network/multus.go
  pkg/network/openshift_sdn.go
Labels: approved, lgtm, size/M

#118 New namespaces for Service Catalog
  bindata/network/openshift-sdn/004-multitenant.yaml
Labels: approved, lgtm, size/S

#123 network: don't allow changing DisableMultiNetwork
  pkg/network/render.go
Labels: approved, lgtm, size/XS

#124 Remove networks.config.openshift.io which is already instantiated by cluster-config-operator
  manifests/0000_07_cluster-network-operator_01_crd.yaml
Labels: approved, lgtm, size/S

#121 Bug 1687973: Fix operator status during upgrade
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
Labels: approved, lgtm, size/M

#127 mount hosts / in sdn image
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/XS

#128 specify the same location for the openshift-sdn binary
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/XS

#119 Adds parameter to set multus log level to verbose in multus.yaml
  bindata/network/multus/multus.yaml
Labels: approved, lgtm, size/XS

#131 Remove hardcoded 'amd64' from Dockerfile to support multi-arch builds.
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#84 add additional NetworkType openshiftSRIOV
  bindata/network/additional-networks/raw/network-attachment.yaml
  bindata/network/additional-networks/sriov/000-ns.yaml
  bindata/network/additional-networks/sriov/002-rbac.yaml
  bindata/network/additional-networks/sriov/network-attachment.yaml
  bindata/network/additional-networks/sriov/sriov-cni.yaml
  bindata/network/additional-networks/sriov/sriov-device-plugin.yaml
  manifests/0000_07_cluster-network-operator_03_daemonset.yaml
  manifests/image-references
  pkg/network/additional_networks.go
  pkg/network/additional_networks_test.go
  pkg/network/render.go
  pkg/network/sriov.go
Labels: approved, lgtm, size/L

#130 DHCP Daemon
  bindata/network/multus/003-dhcp-daemon.yaml
  pkg/network/dhcp_daemon.go
  pkg/network/dhcp_daemon_test.go
  pkg/network/multus.go
  pkg/network/render.go
Labels: approved, lgtm, size/L

#44 Initial support for ovn-kubernetes
  README.md
  bindata/network/ovn-kubernetes/000-ns.yaml
  bindata/network/ovn-kubernetes/002-rbac.yaml
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/004-config.yaml
  bindata/network/ovn-kubernetes/005-service.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  manifests/0000_07_cluster-network-operator_03_daemonset.yaml
  manifests/image-references
  pkg/network/cluster_config.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
Labels: approved, lgtm, size/XXL

#134 fix mount path for sriov device plugin socket
  bindata/network/additional-networks/sriov/sriov-device-plugin.yaml
Labels: approved, lgtm, size/XS
