Repository openshift/cluster-network-operator, pull requests merged in 2019-12, with the labels that each got.

#406 Bug 1773870: Check if infra.Status.PlatformStatus exists before accessing it
  pkg/util/proxyconfig/no_proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#401 Bug 1779183: Don't mark the operator un-Available or Degraded because of multus-admission-controller
  bindata/network/multus-admission-controller/admission-controller.yaml
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/names/names.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#412 OVN - fix cluster role binding
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
Labels: approved, lgtm, size/XS

#415 Bug 1779133: sdn: Make openshift-user-workload-monitoring global on multitenant
  bindata/network/openshift-sdn/004-multitenant.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#414 ovn-kube: add pod disruption budget, readiness check
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm, size/M

#417 ipv6 stuff part 1
  pkg/network/cluster_config.go
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm, size/S

#418 Bug 1781558: Check if infra.Status.PlatformStatus exists before accessing it
  pkg/util/proxyconfig/no_proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#407 Bug 1778235: network operator crashes when infra.status.platformStatus is missing
  pkg/util/proxyconfig/no_proxy.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#423 Bug 1754046: Modif kuryr-admission-controller pod definition
  bindata/network/kuryr/001-rbac.yaml
  bindata/network/kuryr/009-admission-controller.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#426 run-locally: rebuild the CNO
  hack/run-locally.sh
Labels: approved, lgtm, size/XS

#419 Use app label instead of name on ovnkube-master ds
  bindata/network/ovn-kubernetes/005-service.yaml
  bindata/network/ovn-kubernetes/monitor.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm, size/S

#427 osdn, ovnk: add publishNotReadyAddresses to metrics services
  bindata/network/openshift-sdn/monitor.yaml
  bindata/network/ovn-kubernetes/monitor.yaml
Labels: approved, lgtm, size/XS

#420 Bug 1781707: openshift-sdn, CNO: handle new kubeconfig path
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/S

#435 ovn: use app label instead of name for master metrics and quorum guard
  bindata/network/ovn-kubernetes/monitor.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, size/XS

#436 ovn: fix master control plane job name
  bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
Labels: approved, size/XS

#333 OVN: use config file via ConfigMap rather than environment variables
  bindata/network/ovn-kubernetes/004-config.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm, size/L
