Repository openshift/cluster-network-operator, pull requests merged in 2019-11, with the labels that each got.

#379 multus: copy RHEL8 binaries on FCOS
  bindata/network/multus/multus.yaml
Labels: approved, lgtm, size/S

#211 Add OpenStack credentials request
  manifests/0000_70_cluster-network-operator_01_credentialsrequest.yaml
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, lgtm, size/S

#381 ovn/master: enable unidling
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm, size/XS

#380 adding initial alert rules to ovnkubernetes
  bindata/network/ovn-kubernetes/alert-rules.yaml
Labels: approved, lgtm, size/M

#346 OpenShiftSDN: introduce OVS anti-selector
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, lgtm, size/XS

#378 ovn-kubernetes: add basic control plane alerts
  bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
Labels: approved, lgtm, size/M

#377 Add Prometheus capability to a multus admission controller
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/multus-admission-controller/monitor.yaml
  bindata/network/multus-admission-controller/rules.yaml
  bindata/network/multus/000-ns.yaml
  pkg/network/multus_admission_controller_test.go
Labels: approved, lgtm, size/L

#386 Add "node.kubernetes.io/network-unavailable" toleration to master
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm, size/XS

#371 Bug 1769412: pkg/controller/operconfig/operconfig_controller: Add operator namespace to relatedObjects
  pkg/controller/operconfig/operconfig_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#388 Bug 1766066: Revert "Merge pull request #334 from danehans/bz_1758656"
  pkg/util/proxyconfig/no_proxy.go
  pkg/util/proxyconfig/no_proxy_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#385 Bug 1761609: Remove SDN ds liveness check
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#389 Bug 1725832: The Multus binary should be copied based on the host operating system
  bindata/network/multus/multus.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#349 Bug 1760790: Fix dereference in macvlan IPAM validation function (backport 4.2)
  pkg/network/additional_networks.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#376 SDN-551: RAFT implementation for OVN Openshift
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/bootstrap/types.go
  pkg/network/bootstrap.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
Labels: approved, lgtm, size/L

#395 pkg/controller/configmap_ca_injector: "proxy not found" -> "ConfigMap ... not found"
  pkg/controller/configmap_ca_injector/controller.go
Labels: approved, lgtm, size/XS

#390 more accuratly alert on a single nodes iptable stale
  bindata/network/openshift-sdn/alert-rules.yaml
Labels: approved, lgtm, size/XS

#358 controller/status: set Degraded if rollout is hung.
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
Labels: approved, lgtm, size/XL

#393 Use consolidated sdn-node/sdn-controller image
  HACKING.md
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/openshift-sdn/sdn.yaml
  hack/run-locally.sh
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
  pkg/network/openshift_sdn.go
Labels: approved, lgtm, size/M

#396 Change ovnkube-node.yaml to getent ahostsv4
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, size/XS

#394 change to use IP address instead of hostname for nb and sb db creation
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm, size/S

#399 GCP add ClusterRoleBinding to permit changing node/status
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
Labels: approved, lgtm, size/XS

#405 Bug 1770223: Reverts PR #388
  pkg/util/proxyconfig/no_proxy.go
  pkg/util/proxyconfig/no_proxy_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, priority/critical-urgent, size/S
