Repository openshift/cluster-network-operator, pull requests merged in 2019-05, with the labels that each got.

#167 docs: remove development docs from README to HACKING
  HACKING.md
  README.md
Labels: approved, lgtm, size/L

#164 run-locally.sh fixes
  hack/run-locally.sh
Labels: approved, lgtm, size/S

#166 OVN Kubernetes fixes
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/cluster_config.go
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm, size/M

#168 Make srio-device-plugin tolerations match sriov-cni
  bindata/network/additional-networks/sriov/sriov-device-plugin.yaml
Labels: approved, lgtm, size/XS

#169 cmd: exit 0 on graceful shutdown
  cmd/cluster-network-operator/main.go
Labels: approved, lgtm, size/XS

#170 pkg/apply: copy over auto-generated imagePullSecrets for ServiceAccounts
  pkg/apply/merge.go
Labels: approved, lgtm, size/XS

#171 Update run-locally.sh for manifest renumbering
  hack/run-locally.sh
Labels: approved, lgtm, size/XS

#172 More ovn-kubernetes fixes
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/005-service.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, size/M

#173 Don't set a network status at all if we're not managing networking.
  pkg/controller/operconfig/cluster.go
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
Labels: approved, lgtm, size/S

#174 bindata: add resource requests to multus DS pods
  bindata/network/multus/multus.yaml
Labels: approved, lgtm, size/XS

#160 Only run update logic if objects are actually different
  pkg/apply/apply.go
  pkg/apply/merge.go
Labels: approved, lgtm, size/M

#175 Give the ability to patch nodes to openshift-sdn
  bindata/network/openshift-sdn/002-rbac.yaml
Labels: approved, lgtm, size/XS

#180 openshift-sdn: make host mount read-only
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/XS

#181 openshift-sdn: ovs shutdown ordering.
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, lgtm, size/S

#183 Revert "openshift-sdn: ovs shutdown ordering."
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, lgtm, size/S
