Repository openshift/cluster-network-operator, pull requests merged in 2020-12, with the labels that each got.

#892 Annotate manifests for single-node-developer cluster profile
  hack/update-codegen.sh
  manifests/0000_70_cluster-network-operator_00_namespace.yaml
  manifests/0000_70_cluster-network-operator_01_crd.yaml
  manifests/0000_70_cluster-network-operator_01_credentialsrequest.yaml
  manifests/0000_70_cluster-network-operator_01_pki_crd.yaml
  manifests/0000_70_cluster-network-operator_02_rbac.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/0000_70_cluster-network-operator_04_clusteroperator.yaml
Labels: approved, lgtm

#891 ovn rbac for endpoint slices
  bindata/network/ovn-kubernetes/002-rbac.yaml
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
Labels: approved, lgtm

#894 increasing logging when waiting for Masters during bootstrap for OVN
  pkg/network/bootstrap.go
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm

#895 Bug 1890630: Ensure LimitedPortsOnNetwork is only triggered when needed
  bindata/network/kuryr/alert-rules.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#880 Assign openshift sdn traffic to system priority level
  manifests/0000_70_cluster-network-operator_04_kubeapiserver_flowschema.yaml
  manifests/0000_70_cluster-network-operator_05_clusteroperator.yaml
Labels: approved, lgtm

#900 Fix IPsec CI
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm

#856 Add connectivity checker controller
  bindata/network-diagnostics/000-ns.yaml
  bindata/network-diagnostics/001-rbac.yaml
  bindata/network-diagnostics/network-check-source.yaml
  bindata/network-diagnostics/network-check-target.yaml
  go.sum
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
  pkg/controller/connectivitycheck/connectivity_check_controller.go
  pkg/controller/connectivitycheck/connectivity_check_template.go
  pkg/controller/eventrecorder/event_recorder.go
  pkg/controller/pki/event_recorder.go
  pkg/controller/pki/pki_controller.go
  pkg/network/render.go
  pkg/operator/operator.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_template.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go
  vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go
  vendor/modules.txt
Labels: approved, lgtm

#903 hack: fix run-locally
  hack/run-locally.sh
Labels: approved, lgtm

#908 Bug 1905792: changes to egressfirewall CRD to accommodate DNS names
  bindata/network/ovn-kubernetes/001-crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#889 Bug 1777038: Add alerting rules for subnet allocations
  bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#898 Bug 1907454: install podnetworkconnectivitycheck crd
  Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#914 Bug 1874638: Add -F flag for ovn-nbctl logging
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#926 Bug 1909791: Standlone kube-proxy needs to list EndpointSlices now
  bindata/kube-proxy/001-rbac.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
