Repository openshift/cluster-network-operator, pull requests merged in 2020-05, with the labels that each got.

#562 Bug 1831112: Kuryr: Mount /run/netns to ensure netns access
  bindata/network/kuryr/005-daemon.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#611 Bug 1831680: Prevent patching the HybridOverlayConfig after install time
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#612 Bug 1829824: Remove dead member from LB pool.
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/loadbalancer.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#619 Bug 1832305: Kuryr: Remove old SG rules on upgrade
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/networking.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#622 Bug 1829824: Fix for wrong client passed to the purgeOpenStackLbPoolMember function.
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#620 bug 1831006: For third party plugins enable testing of IPv6 single stack
  pkg/network/kube_proxy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#630 Bug 1833372: Drop 'dep verify' from verify-style
  hack/verify-style.sh
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#623 Bug 1832899: Kuryr: Remove old SG rules on upgrade
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#631 Bug 1834473: ovnkube: set NB/SB database inactivity probes to 60 seconds
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#627 OWNERS: add abhat
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#621 Bug 1832311: Kuryr: Tighten security groups
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#637 Bug 1834858: Kuryr: Remove old SG rules on upgrade
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#638 Bug 1836175: Bump ovn-kind-cno.sh script to use 4.5 image
  hack/ovn-kind-cno.sh
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#635 Bug 1826339: openshift-sdn: rethink kube-proxy rules, fix spurious alerts
  bindata/network/openshift-sdn/alert-rules.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#643 Bug 1834473: ovnkube: really set NB/SB database inactivity probes to 60 seconds
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#634 Bug 1834247: Don't override containernetworking binaries in SDN and Kuryr
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/multus/multus.yaml
  bindata/network/openshift-sdn/sdn.yaml
  pkg/network/multus.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#625 Bug 1807648: Fixes to reliably save/restore flows
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#641 Bug 1820472: Not delete namespace object when cleanup not rended objects
  pkg/controller/statusmanager/status_manager.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#645 Bug 1838251: The DHCP CNI daemonset should mount the netns paths
  bindata/network/multus/003-dhcp-daemon.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#649 Bug 1839733: bindata/network/ovn-kubernetes/ovnkube-: update resource requests
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#607 Bug 1829233: Recreate DNS service upon Octavia upgrade
  bindata/network/kuryr/003-config.yaml
  pkg/bootstrap/types.go
  pkg/names/names.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#636 Bug 1834474: ovnkube: set NB/SB database inactivity probes to 60 seconds
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#650 Bug 1837575: Allow connection between authentication net namespaces
  bindata/network/openshift-sdn/004-multitenant.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#626 Bug 1807670: Fixes to reliably save/restore flows
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
