Repository openshift/cluster-network-operator, pull requests merged in 2020-01, with the labels that each got.

#341 ovn custom geneve port number
  HACKING.md
  README.md
  bindata/network/ovn-kubernetes/004-config.yaml
  manifests/0000_70_cluster-network-operator_01_crd.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, lgtm, size/M

#437 Remove some unwanted logging. Fix an error message
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm, size/M

#440 ovn: container env variables need quotes
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, size/XS

#357 OVNKubernetes: introduce OVS anti-selector
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, ok-to-test, size/L

#439 Support ovn2.12
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, size/M

#442 Fix dhcp daemon api version
  bindata/network/multus/003-dhcp-daemon.yaml
Labels: approved, lgtm, size/XS

#443 Change the metrics port for OVN-Kubernetes
  bindata/network/ovn-kubernetes/monitor.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm, size/XS

#424 ipv6 stuff part 2
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, lgtm, size/L

#422 Allow changing LogLevel online in Kuryr
  bindata/network/kuryr/004-daemon.yaml
  bindata/network/kuryr/005-controller.yaml
  pkg/network/kuryr.go
  pkg/util/k8s/unstructured.go
Labels: approved, lgtm, size/M

#444 Bug 1791277: Stop deploying kuryr-admission-controller if double listeners supported
  bindata/network/kuryr/006-service.yaml
  bindata/network/kuryr/007-admission.secret.yaml
  bindata/network/kuryr/008-webhook.secret.yaml
  bindata/network/kuryr/009-admission-controller.yaml
  bindata/network/kuryr/010-webhook.yaml
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#451 sdn: use the correct socket path
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/XS

#448 Support CA certificate provided by user
  bindata/network/kuryr/003-config.yaml
  bindata/network/kuryr/004-user-ca-cert.yaml
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/kuryr/006-controller.yaml
  bindata/network/kuryr/007-service.yaml
  bindata/network/kuryr/008-admission.secret.yaml
  bindata/network/kuryr/009-webhook.secret.yaml
  bindata/network/kuryr/010-admission-controller.yaml
  bindata/network/kuryr/011-webhook.yaml
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, lgtm, size/M

#452 Add rcarrillocruz as approver
  OWNERS
Labels: approved, lgtm, size/XS

#438 Allow to change the cluster default network type
  pkg/controller/operconfig/operconfig_controller.go
  pkg/names/names.go
Labels: approved, lgtm, size/S

#458 Bug 1769015: Add preserveUnknownFields to CRDs
  bindata/network/openshift-sdn/001-crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#454 Bug 1796514: Adds openAPIV3Schema to NetworkAttachmentDefinitions
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#461 Bug 1796718: ovn: use ovs-appctl ovsdb-server/sync-status for NB/SB DB readiness
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#459 Bug 1796616: Put brackets around IPv6 addresses passed to ovn-ctl
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S
