Repository openshift/cluster-network-operator, pull requests merged in 2020-02, with the labels that each got.

#460 Bug 1796562: sdn/ovn: don't allow ovs-vswitchd to clean up datapath flows on exit
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#445 Bug 1798191: Bump to ovn2.12
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#463 [release-4.3] Bug 1796822: Support deployment on OpenStack with self-signed certificate
  bindata/network/kuryr/003-config.yaml
  bindata/network/kuryr/004-user-ca-cert.yaml
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/kuryr/006-controller.yaml
  bindata/network/kuryr/007-service.yaml
  bindata/network/kuryr/008-admission.secret.yaml
  bindata/network/kuryr/009-webhook.secret.yaml
  bindata/network/kuryr/010-admission-controller.yaml
  bindata/network/kuryr/011-webhook.yaml
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, priority/critical-urgent, size/M

#450 Bug 1792309: IPv6 backports for 4.3
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/bootstrap/types.go
  pkg/network/cluster_config.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#416 Bug 1778314: False Alarm - SDN pod has gone too long without syncing iptables rule
  bindata/network/openshift-sdn/alert-rules.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#431 [release-4.2] Bug 1785728: openshift-sdn, CNO: handle new kubeconfig path
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#457 Bug 1796114: Kuryr: Do not reconfigure if LB providers change
  bindata/network/kuryr/003-config.yaml
  pkg/names/names.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#468 Bug 1800633: Ensure etcd and authentication operator resolves dns over TCP
  bindata/network/kuryr/010-admission-controller.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#471 Bug 1801802: [4.3] Put brackets around IPv6 addresses passed to ovn-ctl
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#473 Bug 1802596: Remove erroneous ovnkube node command-line args
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#470 Bug 1779863: backport ovn-controller rbac fix to 4.3
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#465 bug 1803193: Tighten security groups
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#479 Bug 1802606: pkg/util: Fix URI validation to modern standards
  pkg/util/validation/network.go
  pkg/util/validation/network_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#441 Adding run-remotely.sh script
  hack/run-locally.sh
Labels: approved, lgtm, size/M

#486 Bug 1804734: Kuryr: Disable multiple listeners for OVN provider
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#462 Kuryr: Handle unexpected errors fetching CA cert
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, lgtm, size/S

#453 Kuryr bootstrap code split
  pkg/platform/openstack/identity.go
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/loadbalancer.go
  pkg/platform/openstack/networking.go
Labels: approved, lgtm, size/XXL

#466 Bug 1803697: Changing OVN DB readinessProbe to check membership status instead of DB status
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#490 Bug 1797894: Add MachineNetworks to proxy.status.noPoxy
  pkg/util/proxyconfig/no_proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#493 fix multi-net-spec Network CRD std URL
  README.md
Labels: approved, lgtm, size/XS

#474 Update admission controller progression messaging
  pkg/controller/statusmanager/pod_status.go
Labels: approved, lgtm, size/XS

#449 Bug 1791278: Stop deploying kuryr-admission-controller if double listeners supported #
  bindata/network/kuryr/007-service.yaml
  bindata/network/kuryr/008-admission.secret.yaml
  bindata/network/kuryr/009-webhook.secret.yaml
  bindata/network/kuryr/010-admission-controller.yaml
  bindata/network/kuryr/011-webhook.yaml
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#483 Bug 1806009: Backport ovn-kubernetes-related changes to 4.3
  README.md
  bindata/network/ovn-kubernetes/004-config.yaml
  bindata/network/ovn-kubernetes/005-service.yaml
  bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/monitor.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#476 Bug 1807638: Minimize disruption to pod network while OVS is being upgraded
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#503 Bug 1797894: Don't add empty MachineCIDR to noProxy
  pkg/util/proxyconfig/no_proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#484 Bug 1805987: Uses the readiness indicator file option for Multus
  bindata/network/multus/multus.yaml
  pkg/network/multus.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#507 Bug 1805774: Use the readiness indicator file option for Multus
  bindata/network/multus/multus.yaml
  pkg/network/multus.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#485 Bug 1805444: Uses the readiness indicator file option for Multus [backport 4.3]
  bindata/network/multus/multus.yaml
  pkg/network/multus.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#504 [release-4.3] Bug 1805726: Add MachineNetworks to proxy.status.noProxy
  pkg/util/proxyconfig/no_proxy.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S
