Repository openshift/cluster-network-operator, pull requests merged in 2020-11, with the labels that each got.

#772 Bug 1874638: Fixes missing nbctl daemon logging
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm

#859 Bug 1893362: Ensure tail processes exit with parent
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#853 Detect Nodes Network MTU on Installations with Kuryr
  bindata/network/kuryr/003-config.yaml
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/networking.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/results.go
  vendor/modules.txt
Labels: approved, lgtm

#867 Bug 1891716: Remove spurious label in the pod selector of the master daemonset.
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#873 Add operator.openshift.io/v1/network to relatedObjects for must-gather
  pkg/controller/operconfig/operconfig_controller.go
Labels: approved, lgtm

#815 Add egress-router-cni init container
  bindata/network/multus/multus.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
  pkg/network/multus.go
Labels: approved, lgtm

#881 Build check-endpoints in Dockerfile
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm

#874 Add IBM Cloud managed annotations to CVO manifests
  hack/update-codegen.sh
  manifests/0000_70_cluster-network-operator_00_namespace.yaml
  manifests/0000_70_cluster-network-operator_01_crd.yaml
  manifests/0000_70_cluster-network-operator_01_credentialsrequest.yaml
  manifests/0000_70_cluster-network-operator_01_pki_crd.yaml
  manifests/0000_70_cluster-network-operator_02_rbac.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/0000_70_cluster-network-operator_04_clusteroperator.yaml
Labels: approved, lgtm

#879 Simplify kube-rbac-proxy startup script
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm

#883 Kuryr: Allow changes to KuryrConfig
  pkg/network/kuryr.go
Labels: approved, lgtm

#871 Bug 1887462: Add ovn-db-pod label on the master pods
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
