Repository openshift/cluster-network-operator, pull requests merged in 2020-09, with the labels that each got.

#764 Bug 1872750: ovn-k: add prestop actions for nbdb and sbdb
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#769 Bug 1874242: Revert "Bug 1857387: Do not reset the election-timer value"
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#771 Bug 1874647: Initialize controller-runtime logging
  cmd/cluster-network-operator/log.go
  cmd/cluster-network-operator/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#751 Bug 1870711: Move metrics to SDN DS
  bindata/network/openshift-sdn/002-rbac.yaml
  bindata/network/openshift-sdn/monitor.yaml
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#734 Bug 1861412: NetworkAttachmentDefinitions should have output for "oc explain"
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#767 Enable EgressIP for OpenShift
  bindata/network/ovn-kubernetes/004-config.yaml
Labels: approved, lgtm

#783 Bug 1876566: Add provider information to the kuryrloadbalancer CRD
  bindata/network/kuryr/002-crds.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#755 Bug 1874385: OVN: Handle OVN db upgrades.
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, ok-to-test

#735 Bug 1823709: [backport 4.4] NetworkAttachmentDefinitions should have output for "oc explain"
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#777 Bug 1874591: autodect mtu support for ipv6
  pkg/network/mtu.go
  pkg/network/render.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#787 Bug 1852593: SDN mount host's /var/run/netns
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#770 Bug 1874457: Ensure router is present when Kuryr is used
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/networking.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#792 Bug 1878725: Ensure iptables commands are available on cni init container
  bindata/network/kuryr/005-daemon.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#790 Bug 1868444: Fixes providing empty slice for HybridClusterNetwork
  pkg/network/ovn_kubernetes.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#779 Bug 1874737: [release-4.5] OVN: Handle OVN db upgrades
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#766 Bug 1880490: change the hybrid overlay config to use the ConfigMap instead of cli
  bindata/network/ovn-kubernetes/004-config.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#798 Bug 1880853: Fix oc explain for operatorPKI
  manifests/0000_70_cluster-network-operator_01_pki_crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#796 Bug 1879910: openshift-sdn: bump EgressNetworkPolicy maxItems to 1000
  bindata/network/openshift-sdn/001-crd.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#802 Add trozet to owners
  OWNERS
Labels: approved, do-not-merge/hold, lgtm

#793 Bug 1854306: Run ovn in shared gw mode when configure-ovs.sh run with parameter OVNKubernetes
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#781 Bug 1875438: [release-4.4] OVN: Handle OVN db upgrades
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#803 Bug 1854306: Set a 30s timeout for kubectl command in ovnkube-node
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#804 Bug 1882071: Fix bug in reflector not recovering from "Too large resource version"
  go.mod
  go.sum
  pkg/network/kube_proxy_test.go
  pkg/network/openshift_sdn_test.go
  pkg/util/k8s/kubeproxy_test.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/kube-proxy/config/v1alpha1/types.go
  vendor/k8s.io/kube-proxy/config/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#806 Bug 1882569: Add support for OVN DB Management
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#785 Bug 1874696: Remove systemctl calls
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#812 Bug 1883662: Tune sb-db raft cluster election-timer
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#786 Bug 1883903:Add retries to SDN's RBAC proxy
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
