Repository openshift/cluster-network-operator, pull requests merged in 2020-06, with the labels that each got.

#614 Fix 'complete' typo in README
  README.md
Labels: approved, lgtm, ok-to-test

#617 Use markdown relative link in README.md for HACKING.md reference
  README.md
Labels: approved, lgtm, ok-to-test

#652 Bug 1835497 : Prevent sb/nb db readiness probe from being zombie
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm

#647 fix up dual-stack Service reconciling
  pkg/apply/merge.go
  pkg/apply/merge_test.go
Labels: approved, lgtm

#657 Bug 1841507: Allow connection between authentication net namespaces
  bindata/network/openshift-sdn/004-multitenant.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#660 Improve IPv6 testing and minor fixes
  pkg/network/kube_proxy_test.go
  pkg/util/k8s/kubeproxy.go
Labels: approved, lgtm

#632 Expose Kuryr metrics endpoints to Prometheus server
  bindata/network/kuryr/000-ns.yaml
  bindata/network/kuryr/003-config.yaml
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/kuryr/006-controller.yaml
  bindata/network/kuryr/monitor.yaml
Labels: approved, lgtm

#661 Bug 1824983: explicitly delete pidfiles when exiting
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#653 Bug 1841029: Recreate DNS service upon Octavia upgrade
  bindata/network/kuryr/003-config.yaml
  pkg/bootstrap/types.go
  pkg/names/names.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#629 Bug 1832872: Remove dead member from LB pool.
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/loadbalancer.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#569 Logging: add time stamp to echo in cno yaml
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm

#656 Bug 1846396: Drop ovn-octavia provider limitation for multiprotocol listeners
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#674 ovn-kubernetes: allow dual-stack configs
  bindata/network/ovn-kubernetes/004-config.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  vendor/k8s.io/utils/net/ipnet.go
  vendor/k8s.io/utils/net/net.go
  vendor/modules.txt
Labels: approved, lgtm

#671 Bug 1847313: Split etcd sg rule ports range into different sg rules
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#613 Bug 1798887: Fixes Proxy ReadinessEndpoints Validation
  pkg/controller/proxyconfig/validation.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#668 Mark operator as degraded if there are any pods in CrashLoopBackOff State
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/status_manager_test.go
Labels: approved, lgtm

#672 openshift-sdn, ovn-kubernetes: adopt systemd-managed openvswitch if present
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
Labels: approved, lgtm

#669 Bug 1847675: [4.4] mount /var/run/netns rslave in ovnkube
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#615 Bug 1822296: Expose raft (nb-db/sb-db) election-timer and ovn-controller inactivit…
  .gitignore
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  pkg/network/ovn_kubernetes.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#667 Bug 1846459: Recreate DNS service upon Octavia upgrade
  bindata/network/kuryr/003-config.yaml
  pkg/bootstrap/types.go
  pkg/names/names.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#682 Bug 1851518: Expose raft (nb-db/sb-db) election-timer and ovn-controller inactivity probe.
  .gitignore
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  pkg/network/ovn_kubernetes.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
