Repository openshift/cluster-network-operator, pull requests merged in 2020-04, with the labels that each got.

#560 Remove logfile from ovnkube configmap as to avoid log rotation
  bindata/network/ovn-kubernetes/004-config.yaml
Labels: approved, lgtm

#570 OWNERS: add bugzilla info
  OWNERS
Labels: approved, lgtm

#564 Bug 1818029: Stop waiting for failed loadbalancer.
  pkg/platform/openstack/loadbalancer.go
Labels: approved, bugzilla/valid-bug, lgtm

#563 Bug 1817562: Configure tls for multus metrics endpoint
  bindata/network/multus-admission-controller/001-service.yaml
  bindata/network/multus-admission-controller/002-rbac.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/multus-admission-controller/monitor.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
  pkg/network/multus_admission_controller.go
  pkg/network/multus_admission_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#572 Adds missing OVN NB SSL args to ovnkube master
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm

#575 Allow to only enable hybrid overlay and not handle Windows networks
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm

#566 Bug 1793108: [Back-port] Remove logfile from ovnkube configmap
  bindata/network/ovn-kubernetes/004-config.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#584 Kuryr: Open metric endpoint ports from pod subnets
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, lgtm

#582 ovn: use normal OVN DB address syntax
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm

#586 Adds failsafe for OVN nbctl daemon socket
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm

#578 Bug 1822308: Adds missing OVN NB SSL args to ovnkube master
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#528 Bug 1812678: RBAC for Whereabouts should reference ippools.whereabouts.cni.cncf.io [backport 4.4.z]
  bindata/network/multus/002-rbac.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#588 Bug 1823399: Allow to only enable hybrid overlay and not handle Windows networks
  pkg/network/ovn_kubernetes.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#593 Fix multus metrics endpoint to listen to localhost only
  bindata/network/multus-admission-controller/admission-controller.yaml
Labels: approved, lgtm

#571 Bug 1821128: Stop waiting for failed loadbalancer.
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#592 The NetworkAttachmentDefinition CRD should have description fields
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: approved, lgtm

#567 Bug 1821166: [Back-port 4.3] Remove logfile from ovnkube configmap
  bindata/network/ovn-kubernetes/004-config.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#492 Bug 1775838: Back-port, OVNKubernetes: introduce OVS anti-selector
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#579 mount /var/run/netns rslave in ovnkube
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm

#544 Bug 1802481: Don't override containernetworking binaries in SDN and Kuryr
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/multus/multus.yaml
  bindata/network/openshift-sdn/sdn.yaml
  pkg/network/multus.go
Labels: approved, bugzilla/valid-bug, lgtm

#601 Bug 1826322: sdn: fix typo in openshift-sdn run script
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#603 Bug 1827009: correctly tell ovnkube-node containers the label that hybrid overlay nodes have
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#608 Bug 1825019: Setting resource request for kube-proxy deployment
  bindata/kube-proxy/kube-proxy.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
