Repository openshift/cluster-network-operator, pull requests merged in 2020-07, with the labels that each got.

#680 Bug 1851338: Split etcd sg rule ports range into different sg rules
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#688 Bug 1837953: Check if the db file has been correctly initialized with raft.
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#683 Bug 1848374: Delete flows.sh after restore.
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#690 Bump OVN Bootstrap timeout
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm

#686 Add support for Kuryr alerts
  bindata/network/kuryr/alert-rules.yaml
Labels: approved, lgtm

#692 Bug 1853712: Fix kuryr templates format for ifs
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/kuryr/006-controller.yaml
  pkg/render/funcs.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#689 Bug 1851928: [metrics] TargetDown alert is always fired in ovnkube-node job
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#696 Bug 1852593: Add netns mount
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#698 Bug 1856289: Block MCS and metadata for host-networking pods
  bindata/network/kuryr/005-daemon.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#708 Bug 1856271: Make sure the network metrics pod runs only on linux nodes.
  bindata/network/network-metrics/001-daemonset.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#710 ovn-kubernetes: record ovn-northd pid
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm

#711 Enable multicast support by default on the master
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm

#701 Set timeoutSeconds to reflect expected timeout for OVS commands
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
Labels: approved, lgtm

#663 use KIND multinode cluster , add IPv6 support, fix multus webook problem
  hack/KIND_CNO.md
  hack/ovn-kind-cno.sh
  hack/webhook-create-signed-cert.sh
Labels: approved, lgtm

#707 Disable conntrack for GENEVE
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm

#717 Bug 1855121: mount host-slash HostToContainer
  bindata/kube-proxy/kube-proxy.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#718 Bug 1858712: Revert "[release-4.5] Bug 1854072: Check if the db file has been correctly initialized with raft.
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#694 Bug 1837953: fixup server_id regex
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#712 Bug 1857738: [release-4.5] Set timeoutSeconds to reflect expected timeout for OVS commands
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#574 Bug 1809205: Configure TLS for OpenShift SDN metrics endpoint
  bindata/network/openshift-sdn/002-rbac.yaml
  bindata/network/openshift-sdn/monitor.yaml
  bindata/network/openshift-sdn/sdn.yaml
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#723 Bug 1858834: Revert ovn db consistency check.
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#724 Bug 1857742: [release-4.4] Set timeoutSeconds to reflect expected timeout for OVS commands
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#726 Multus whereabouts IPAM CNI should support overlapping ranges
  bindata/network/additional-networks/crd/001-crd.yaml
  bindata/network/multus/002-rbac.yaml
  pkg/network/additional_networks_test.go
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: approved, lgtm

#581 Bug 1822720: Configure TLS for OVN metrics endpoints
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/monitor.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: approved, bugzilla/valid-bug, lgtm

#640 Support using common name as hostname for TLS server cert verification
  bindata/network/ovn-kubernetes/006-pki.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm

#722 Bug 1859374: Disable conntrack for GENEVE
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#732 Kuryr: Add new Custom Resource Definitions
  bindata/network/kuryr/001-rbac.yaml
  bindata/network/kuryr/002-crds.yaml
  bindata/network/kuryr/003-config.yaml
Labels: approved, lgtm

#737 Add required setup for egressFirewall and egressIP
  bindata/network/ovn-kubernetes/001-crd.yaml
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
Labels: approved, lgtm
