Repository openshift/cluster-network-operator, pull requests merged in 2021-02, with the labels that each got.

#963 Bug 1920159: Reduce CPU requests of ovs daemonset
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#965 Bug 1920769: override the default node-selector for network-connectivity check
  bindata/network-diagnostics/000-ns.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#966 Bug 1905730: ipsec: Suppress benign error messages on startup of ovs-monitor-ipsec
  bindata/network/ovn-kubernetes/ipsec.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#972 Bug 1920769: Fix the spacing for the node-selector override annotation
  bindata/network-diagnostics/000-ns.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#973 Bug 1924383: update the resource requests made by pods in openshift-network-diagnostics namespace
  bindata/network-diagnostics/network-check-source.yaml
  bindata/network-diagnostics/network-check-target.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#960 Bug 1918375: Add tokenreviews permissions for kube-proxy
  bindata/kube-proxy/001-rbac.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#970 Bug 1912820: competing connectivitycheckcontrollers cause pod restarts during upgrades
  Dockerfile
  Dockerfile.rhel7
  go.mod
  go.sum
  pkg/controller/connectivitycheck/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#655 Bug 1838343 - Improve the sb-db and nb-db readiness check to ensure it fails when cluster is not stable.
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, lgtm

#967 Bug 1924137: Increase the initialDelaySeconds for liveness and readiness probes
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#969 Bug 1921184: Kuryr: Let Kuryr autodetect primary CNI interface
  bindata/network/kuryr/003-config.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#971 Suppress sleep message in ovn-ipsec container
  bindata/network/ovn-kubernetes/ipsec.yaml
Labels: approved, lgtm

#953 Bug 1916601: guard against the deletion of the network CRD: `network.operator.openshift.io`
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#937 : Bug 1913399: Bump flow control apiVersion to beta
  bindata/network/openshift-sdn/006-flowschema.yaml
  bindata/network/ovn-kubernetes/007-flowschema.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#980 Bug 1927244: Kuryr: Always set worker_nodes_subnets
  bindata/network/kuryr/003-config.yaml
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#962 Bug 1920209: The pods in the Multus daemonset should exit in a reasonable time during an upgrade.
  bindata/network/multus/multus.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#985 Bug 1924425: Update protobuf version to address CVE-2021-3121
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/event/core/event.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#984 Enable golangci-lint; fix up lint issues
  .golangciversion
  .vscode/settings.json
  Makefile
  cmd/cluster-network-operator/main.go
  hack/verify-style.sh
  pkg/apply/merge.go
  pkg/apply/merge_test.go
  pkg/cmd/checkendpoints/controller/connection_checker_test.go
  pkg/cmd/checkendpoints/operatorcontrolplane/podnetworkconnectivitycheck/v1alpha1helpers/helpers_test.go
  pkg/cmd/checkendpoints/trace/latency.go
  pkg/controller/clusterconfig/clusterconfig_controller.go
  pkg/controller/configmap_ca_injector/controller.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/pki/pki_controller.go
  pkg/controller/proxyconfig/controller.go
  pkg/controller/signer/signer-controller.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/network/additional_networks.go
  pkg/network/dhcp_daemon.go
  pkg/network/openshift_sdn.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render.go
  pkg/operator/operator.go
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/util/validation/trustbundle.go
Labels: approved, lgtm

#964 Bug 1908916: disable ovsdb column diffs if supported
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#976 cmd: stop using URL_ONLY_KUBECONFIG
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: approved, lgtm
