Repository openshift/cluster-network-operator, pull requests merged in 2021-11, with the labels that each got.

#1207 Bug 1914053: whereabouts: add ip-reconciler cronjob
  bindata/network/multus/002-rbac.yaml
  bindata/network/multus/multus.yaml
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1161 Bug 1976399: Raft election timer: move the logic to ovndbchecker
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1219 Bug 1962206: DHCP daemon should have maxunavailable for upgrade strategy
  bindata/network/multus/003-dhcp-daemon.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1222 Add ip6tables NOTRACK rules for udp/6081
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved

#1218 Bug 1961509: DHCP Daemon should have memory and CPU limits set
  bindata/network/multus/003-dhcp-daemon.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1205 Add bond-cni
  bindata/network/multus/multus.yaml
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
  pkg/network/multus.go
Labels: lgtm, approved

#1224 bindata/network: specify pod-security levels via labels not annotations
  bindata/network/multus/000-ns.yaml
  bindata/network/openshift-sdn/000-ns.yaml
Labels: lgtm, approved

#1233 update for ART
  .ci-operator.yaml
  Dockerfile.rhel7
  pkg/apis/network/v1/zz_generated.deepcopy.go
  pkg/dependencymagnet/dependencymagnet.go
  pkg/network/mtu.go
  pkg/network/mtu_unsupported.go
Labels: lgtm, approved

#1206 Specific SDN controller alert
  bindata/network/openshift-sdn/alert-rules.yaml
Labels: lgtm, approved

#1172 openshift-sdn/daemonset: Mount /host/opt/cni/bin at /host-cni-bin
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved

#1214 Set upgrade strategy on kube-proxy
  bindata/kube-proxy/kube-proxy.yaml
Labels: lgtm, approved

#1213 SDN: Do not tolerate a controller failure during upgrade
  bindata/network/openshift-sdn/controller.yaml
Labels: lgtm, approved
