Repository openshift/cluster-network-operator, pull requests merged in 2021-06, with the labels that each got.

#1095 Bug 1954773: update the cno to use the egressfirewall flag
  bindata/network/ovn-kubernetes/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1116 Bug 1951158: Update egress router CRD from vendor to manifests
  manifests/0000_70_cluster-network-operator_01_egr_crd.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1114 Bug 1965834: add management annotation to multus-additional-cni-plugins pods
  bindata/network/multus/multus.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1107 Bug 1825219: Fix nil checks in bootstrapSDN
  pkg/network/openshift_sdn.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1117 Bug 1951158: Fix generated JSON format
  bindata/egress-router/000-nad.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1087 Bug 1942603: [release-4.7] Allow from router policy support for cluster network operator
  bindata/network/openshift-sdn/openshift-host-network-ns.yaml
  bindata/network/openshift-sdn/openshift-host-network-resourcequota.yaml
  bindata/network/ovn-kubernetes/004-config.yaml
  bindata/network/ovn-kubernetes/openshift-host-network-ns.yaml
  bindata/network/ovn-kubernetes/openshift-host-network-resourcequota.yaml
  pkg/controller/add_networkconfig.go
  pkg/controller/ingressconfig/ingressconfig_controller.go
  pkg/names/names.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1070 Bug 1932114: Detect Nodes Network MTU
  bindata/network/kuryr/003-config.yaml
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/networking.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/results.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1110 Bug 1954870: Add priorityClass to allow user load to preempt tests
  bindata/network-diagnostics/network-check-source.yaml
  bindata/network-diagnostics/network-check-target.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1100 Bug 1955548: Kuryr: Do not expand services subnet with OVN
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/networking.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1125 Bug 1968567: egress router CNI command is missing
  bindata/egress-router/001-deployment.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1118 [release-4.7] Bug 1967388: annotate flowcontrol with `networkoperator.openshift.io/ignore-errors`
  bindata/network/openshift-sdn/006-flowschema.yaml
  bindata/network/ovn-kubernetes/007-flowschema.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1126 Bug 1967933: Add network-tools to image-stream
  manifests/image-references
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1119 Bug 1967994: Backport daemonset to drop icmp frag needed packets received from other nodes in the cluster to Rel 4.7
  bindata/network/openshift-sdn/sdn.yaml
  pkg/bootstrap/types.go
  pkg/network/bootstrap.go
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/render.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1111 Bug 1970453: Replace to correct OpenFlow version when replacing flows
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1099 Add JacobTanenbaum to list of approvers
  OWNERS
Labels: approved, lgtm

#1135 [release-4.6] Bug 1972587: config: Allow enable-profiling to be used to set profiling
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/util/k8s/kubeproxy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1121 Bug 1851549: Backport daemonset to drop icmp frag needed packets received from other nodes in the cluster to Rel 4.6
  bindata/network/openshift-sdn/sdn.yaml
  pkg/bootstrap/types.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/bootstrap.go
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/render.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#1139 Bug 1975016: Kuryr: Store OpenStack credentials in a secret
  bindata/network/kuryr/003-config.yaml
  bindata/network/kuryr/003-credentials.yaml
  bindata/network/kuryr/006-controller.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
