Repository openshift/cluster-network-operator, pull requests merged in 2021-09, with the labels that each got.

#1188 Bug 1997050: Fix panic with unknown networks
  pkg/network/bootstrap.go
  pkg/network/render_test.go
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#1190 Bug 1986061: Monitor openshift-network-diagnostics namespace
  bindata/network-diagnostics/000-ns.yaml
  bindata/network-diagnostics/001-rbac.yaml
  bindata/network-diagnostics/network-check-source.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1191 Bug 1939435: proxyconfig - accept IPv6 address literals for noProxy
  Dockerfile
  pkg/controller/proxyconfig/validation.go
  pkg/util/validation/network.go
  pkg/util/validation/network_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1185 Bug 1990928: [Backport 4.8] Whereabouts should have RBAC for leases
  bindata/network/multus/002-rbac.yaml
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent

#1196 Bug 2002713: Add millisecond resolution to OVN logs
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1173 Bug 1985486: Use proxy to connect to OSP cloud
  bindata/network/kuryr/003-config.yaml
  bindata/network/kuryr/006-controller.yaml
  go.mod
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1132 Bug 1988483: OVN drop icmp frag from other nodes on Azure cluster
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
