Repository openshift/cluster-network-operator, pull requests merged in 2021-04, with the labels that each got.

#1021 Add support for exporting network flows
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm

#1045 Kuryr: Update CRDs from upstream
  bindata/network/kuryr/002-crds.yaml
Labels: approved, lgtm

#993 [SDN-1364] Update CNO for OVN acl audit logging
  README.md
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  go.sum
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, lgtm

#1044 Kuryr: Update OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#1046 Bug 1943649: Add command for network-check-target instead of hello-openshift
  .gitignore
  Dockerfile
  Dockerfile.rhel7
  Makefile
  bindata/network-diagnostics/network-check-target.yaml
  cmd/cluster-network-check-target/main.go
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1048 copy the service network slice
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
Labels: approved, lgtm

#1040 Bug 1944160: ovn: log more info about nbctl daemon database reconnections
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1052 Bug 1936515: Use the election mechanism provided by library-go
  cmd/cluster-network-operator/main.go
  pkg/operator/leader/k8sutil.go
  pkg/operator/leader/leader.go
  pkg/operator/operator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1014 Remove LB management
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/loadbalancer.go
  pkg/platform/openstack/networking.go
Labels: approved, lgtm

#1034 automatic dual-stack conversion
  pkg/names/names.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, lgtm

#1053 Minor cleanups
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, lgtm

#1054 Fix run_locally namespace
  hack/run-locally.sh
Labels: approved, lgtm

#353 Add capabilities in simpleMacvlan's staticIPAM config
  README.md
  pkg/network/additional_networks.go
  pkg/network/additional_networks_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1033 Set the host-network-namespace parameter for ovn-kubernetes
  bindata/network/openshift-sdn/openshift-host-network-ns.yaml
  bindata/network/openshift-sdn/openshift-host-network-resourcequota.yaml
  bindata/network/ovn-kubernetes/004-config.yaml
  bindata/network/ovn-kubernetes/openshift-host-network-ns.yaml
  bindata/network/ovn-kubernetes/openshift-host-network-resourcequota.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#1049 Bug 1949099: Fix up network-check-target
  .gitignore
  bindata/network-diagnostics/network-check-target.yaml
  cmd/cluster-network-check-target/main.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#887 Bug 1948592: Add Egress Router Controller
  bindata/egress-router/000-nad.yaml
  bindata/egress-router/001-deployment.yaml
  pkg/client/client.go
  pkg/controller/add_networkconfig.go
  pkg/controller/egress_router/egress_router_controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1057 Bug 1937594: Bump openshift/api
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/urls.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/apiserver/install.go
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_deprecatedapirequests.yaml
  vendor/github.com/openshift/api/apiserver/v1/doc.go
  vendor/github.com/openshift/api/apiserver/v1/register.go
  vendor/github.com/openshift/api/apiserver/v1/types_deprecatedapirequest.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/cloudnetwork/OWNERS
  vendor/github.com/openshift/api/cloudnetwork/install.go
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml-patch
  vendor/github.com/openshift/api/cloudnetwork/v1/doc.go
  vendor/github.com/openshift/api/cloudnetwork/v1/generated.pb.go
  vendor/github.com/openshift/api/cloudnetwork/v1/generated.proto
  vendor/github.com/openshift/api/cloudnetwork/v1/register.go
  vendor/github.com/openshift/api/cloudnetwork/v1/types.go
  vendor/github.com/openshift/api/cloudnetwork/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/cloudnetwork/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1051 Add management workload annotations
  bindata/kube-proxy/000-ns.yaml
  bindata/kube-proxy/kube-proxy.yaml
  bindata/network-diagnostics/000-ns.yaml
  bindata/network-diagnostics/network-check-source.yaml
  bindata/network-diagnostics/network-check-target.yaml
  bindata/network/kuryr/000-ns.yaml
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/kuryr/006-controller.yaml
  bindata/network/kuryr/010-admission-controller.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/multus-networkpolicy/multus-networkpolicy.yaml
  bindata/network/multus/000-ns.yaml
  bindata/network/multus/003-dhcp-daemon.yaml
  bindata/network/multus/multus.yaml
  bindata/network/network-metrics/001-daemonset.yaml
  bindata/network/openshift-sdn/000-ns.yaml
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/openshift-host-network-ns.yaml
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/000-ns.yaml
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
  bindata/network/ovn-kubernetes/ipsec.yaml
  bindata/network/ovn-kubernetes/openshift-host-network-ns.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  manifests/0000_70_cluster-network-operator_00_namespace.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1007 Bug 1936719: OSD-6600 network-metrics missing priorityClass
  bindata/network/network-metrics/001-daemonset.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#763 Bug 1937594: Split SDN migration into 2 phase
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/cluster_config.go
  pkg/network/render.go
  pkg/network/render_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1063 Bug 1937594: Update the codegen with the latest API
  manifests/0000_70_cluster-network-operator_01_crd.yaml
  manifests/0000_70_cluster-network-operator_01_egr_crd.yaml
  manifests/0000_70_cluster-network-operator_01_pki_crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1069 Bug 1952079: Don't try to disable the EndpointSlice feature gate
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1062 Bug 1942555: Rely on status for ingress controller for endpointPublishingStrategy
  pkg/controller/ingressconfig/ingressconfig_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1028 Bug 1907353: Remove OVS daemonsets
  README.md
  bindata/network/openshift-sdn/alert-rules.yaml
  bindata/network/openshift-sdn/sdn-ovs.yaml
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
  bindata/network/ovn-kubernetes/ipsec.yaml
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1060 Bug 1950094: Upgrade nodes before masters
  pkg/apply/merge.go
  pkg/apply/merge_test.go
  pkg/bootstrap/types.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/names/names.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/semver.go
  pkg/network/semver_test.go
  pkg/network/testutil_test.go
  pkg/util/k8s/unstructured.go
  pkg/util/k8s/unstructured_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1006 Bug 1936710: OSD-6600 network-metrics missing priorityClass
  bindata/network/network-metrics/001-daemonset.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1065 Rename workload annotations
  bindata/egress-router/001-deployment.yaml
  bindata/kube-proxy/kube-proxy.yaml
  bindata/network-diagnostics/network-check-source.yaml
  bindata/network-diagnostics/network-check-target.yaml
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/kuryr/006-controller.yaml
  bindata/network/kuryr/010-admission-controller.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/multus-networkpolicy/multus-networkpolicy.yaml
  bindata/network/multus/003-dhcp-daemon.yaml
  bindata/network/multus/multus.yaml
  bindata/network/network-metrics/001-daemonset.yaml
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ipsec.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm
