Repository openshift/cluster-network-operator, pull requests merged in 2021-03, with the labels that each got.

#999 Bug 1933269: Include LB members for Machines created on day-2 operation
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#997 Bug 1933179: Use 10% for nw-check-target maxUnavailable
  bindata/network-diagnostics/network-check-target.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#995 Bug 1933173: Use 10% for sdn maxUnavailable for rolling update
  bindata/network/openshift-sdn/sdn.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1000 Bug 1934711: Use 10% for ovnkube-node for maxUnavailable
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#994 OSD-6600 network-metrics missing priorityClass
  bindata/network/network-metrics/001-daemonset.yaml
Labels: approved, lgtm

#988 config: Set enable-profiling true by default and allow `enable-profiling` as a proxy argument
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/util/k8s/kubeproxy.go
Labels: approved, lgtm

#996 Bug 1933174: Use 10% for ovs maxUnavailable for rolling update
  bindata/network/openshift-sdn/sdn-ovs.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1009 Bug 1937005: kuryr/alerts: change the rule for free count
  bindata/network/kuryr/alert-rules.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#975 SDN-1571 ipsec: Allow enablement/disablement at runtime
  bindata/network/ovn-kubernetes/ipsec.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
Labels: approved, lgtm

#1015 Fix possible name patterns on regex
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, lgtm

#1002 Bug 1935473: Include LB members for Machines created on day-2 operation
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1003 sdn: Add list/watch RBAC for endpointslices to openshift-sdn
  bindata/network/openshift-sdn/002-rbac.yaml
Labels: approved, lgtm

#959 Allow dual stack migration
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
  pkg/network/render.go
  pkg/network/render_test.go
Labels: approved, lgtm

#1013 Bug 1937452: Fix golangci-lint violations
  pkg/controller/statusmanager/status_manager_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1020 Bug 1938920: Set maxUnavailable for ovs-node daemonset
  bindata/network/ovn-kubernetes/006-ovs-node.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#992 Bug 1933159: The Multus daemonset should handle 10% maxUnavailable
  bindata/network/multus/multus.yaml
  bindata/network/network-metrics/001-daemonset.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1026 Bug 1939752: ovnkube: add missing resource requests for SBDB
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1024 ovn/ipsec: set maxUnavailable to 10%
  bindata/network/ovn-kubernetes/ipsec.yaml
Labels: approved, lgtm

#1017 Bug 1937829: Cherry-pick dual stack migration
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
  pkg/network/render.go
  pkg/network/render_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1027 Bug 1939060: OVN Upgrade: fix upgrade order of node and master
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1023 ovnkube: better logging for upgrades/downgrades
  pkg/network/ovn_kubernetes.go
  pkg/network/semver.go
  pkg/network/semver_test.go
Labels: approved, lgtm

#1004 Bug 1931997: mark network-check-target non critical
  bindata/network-diagnostics/network-check-target.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#968 Update remaining CRDs and webhooks to v1
  bindata/network/additional-networks/crd/001-crd.yaml
  bindata/network/multus-admission-controller/003-webhook.yaml
  bindata/network/openshift-sdn/001-crd.yaml
Labels: approved, lgtm

#923 MultiNetworkPolicy integration
  bindata/network/multus-networkpolicy/001-scheme.yaml
  bindata/network/multus-networkpolicy/002-rbac.yaml
  bindata/network/multus-networkpolicy/multus-networkpolicy.yaml
  manifests/0000_70_cluster-network-operator_01_crd.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
  pkg/network/multi_network_policy.go
  pkg/network/multi_network_policy_test.go
  pkg/network/render.go
Labels: approved, lgtm

#897 Re-enable shared gateway mode
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, lgtm

#1025 Bug 1916809: mount node ovs db for multi-gather gather_network_logs
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#1037 SDN-1249: Bump openshift/api vendoring to pull egressrouter CRD
  go.mod
  go.sum
  hack/update-codegen.sh
  manifests/0000_70_cluster-network-operator_01_crd.yaml
  manifests/0000_70_cluster-network-operator_01_egr_crd.yaml
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/networkoperator/OWNERS
  vendor/github.com/openshift/api/networkoperator/install.go
  vendor/github.com/openshift/api/networkoperator/v1/001-egressrouter.crd.yaml
  vendor/github.com/openshift/api/networkoperator/v1/001-egressrouter.crd.yaml-patch
  vendor/github.com/openshift/api/networkoperator/v1/doc.go
  vendor/github.com/openshift/api/networkoperator/v1/generated.pb.go
  vendor/github.com/openshift/api/networkoperator/v1/generated.proto
  vendor/github.com/openshift/api/networkoperator/v1/register.go
  vendor/github.com/openshift/api/networkoperator/v1/types_egressrouter.go
  vendor/github.com/openshift/api/networkoperator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/networkoperator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#1038 Bug 1905331: Set requests on multus components
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/multus/multus.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#981 Allow from router support in CNO
  bindata/network/openshift-sdn/host-network/ns.yaml
  bindata/network/openshift-sdn/host-network/resourcequota.yaml
  bindata/network/ovn-kubernetes/host-network/ns.yaml
  bindata/network/ovn-kubernetes/host-network/resourcequota.yaml
  pkg/controller/add_networkconfig.go
  pkg/controller/ingressconfig/ingressconfig_controller.go
  pkg/names/names.go
Labels: approved, lgtm
