Repository openshift/cluster-network-operator, pull requests merged in 2021-10, with the labels that each got.

#1200 Bug 2008589: [4.8z] Slow OVN Recovery on SNO
  bindata/network/ovn-kubernetes/004-config.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#1186 Bug 1990932: [Backport 4.7] Whereabouts should have RBAC for leases
  bindata/network/multus/002-rbac.yaml
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent

#1203 podsecurity: enforce privileged for network namespaces
  bindata/kube-proxy/000-ns.yaml
  bindata/network/kuryr/000-ns.yaml
  bindata/network/multus/000-ns.yaml
  bindata/network/openshift-sdn/000-ns.yaml
  bindata/network/ovn-kubernetes/000-ns.yaml
  manifests/0000_70_cluster-network-operator_00_namespace.yaml
Labels: lgtm, approved

#1208 fix a typo in a field name
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved
