Repository openshift/cluster-network-operator, pull requests merged in 2021-08, with the labels that each got.

#1166 Bug 1989122: let openshift-sdn use EndpointSliceProxying
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1081 Remove valadas from owners
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm, lifecycle/stale

#1078 Docs: add architecture overview, remove outdated HACKING guide.
  HACKING.md
  README.md
  docs/architecture.md
Labels: approved, bugzilla/valid-bug, lgtm

#1159 Bug 1984049: Slow OVN Recovery on SNO
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1169 Bug 1988425: Change to use mountPath: /host
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, qe-approved

#1174 Bug 1989734: Whereabouts should have RBAC for leases
  bindata/network/multus/002-rbac.yaml
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1181 Bug 1992507: Use prometheus rule annotations comply with the OpenShift alerting guidelines
  bindata/network/kuryr/alert-rules.yaml
  bindata/network/openshift-sdn/alert-rules.yaml
  bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/alert-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1175 Bug 1989246: use new default leader election values to handle apiserver rollout on SNO
  go.mod
  go.sum
  vendor/github.com/certifi/gocertifi/LICENSE
  vendor/github.com/certifi/gocertifi/README.md
  vendor/github.com/certifi/gocertifi/certifi.go
  vendor/github.com/getsentry/raven-go/.dockerignore
  vendor/github.com/getsentry/raven-go/.gitignore
  vendor/github.com/getsentry/raven-go/.gitmodules
  vendor/github.com/getsentry/raven-go/.travis.yml
  vendor/github.com/getsentry/raven-go/LICENSE
  vendor/github.com/getsentry/raven-go/README.md
  vendor/github.com/getsentry/raven-go/client.go
  vendor/github.com/getsentry/raven-go/errors.go
  vendor/github.com/getsentry/raven-go/exception.go
  vendor/github.com/getsentry/raven-go/http.go
  vendor/github.com/getsentry/raven-go/interfaces.go
  vendor/github.com/getsentry/raven-go/runtests.sh
  vendor/github.com/getsentry/raven-go/stacktrace.go
  vendor/github.com/getsentry/raven-go/writer.go
  vendor/github.com/openshift/library-go/pkg/authorization/hardcodedauthorizer/metrics.go
  vendor/github.com/openshift/library-go/pkg/config/client/transport.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/args.go
  vendor/github.com/openshift/library-go/pkg/serviceability/panic.go
  vendor/github.com/openshift/library-go/pkg/serviceability/sentry.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.pb.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1177 Bug 1991551: allow sdn (and others) to use new events.k8s.io API
  bindata/kube-proxy/001-rbac.yaml
  bindata/network-diagnostics/001-rbac.yaml
  bindata/network/multus/002-rbac.yaml
  bindata/network/openshift-sdn/002-rbac.yaml
  bindata/network/openshift-sdn/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/002-rbac.yaml
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1170 Bug 1988426: Change to use mountPath: /host
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent

#1131 Bug 1973770: Reduce SSL sec level for ovsdb connections
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#1124 Bug 1914398: Changed pod user to non-root
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/network-metrics/001-daemonset.yaml
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, bugzilla/severity-high

#1167 Bug 1987046: Add pre-puller ds to reduce upgrade downtime
  bindata/network/ovn-kubernetes/pre-puller.yaml
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/util/k8s/unstructured.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#1192 Bug 1998508: Fix the install-time "waiting for other operators" statuses
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/status_manager.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
