Repository openshift/cluster-network-operator, pull requests merged in 2021-12, with the labels that each got.

#1171 Bug 1988427: Change to use mountPath: /host
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1238 The ip-reconciler should not restart on failures.
  bindata/network/multus/multus.yaml
Labels: lgtm, approved

#1204 NETOBSERV-31: Expose CNI type features as a config-map
  bindata/network/openshift-sdn/cni-features.yaml
  bindata/network/ovn-kubernetes/cni-features.yaml
  bindata/network/public/000-roles.yaml
  pkg/network/render.go
  pkg/network/render_test.go
Labels: lgtm, approved

#1220 Add CNI to DPU and enable Kube-Proxy on DPU
  bindata/kube-proxy/kube-proxy.yaml
  bindata/network/ovn-kubernetes/error-cni.yaml
  bindata/network/ovn-kubernetes/ipsec.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  hack/dpu-mode.yaml
  pkg/bootstrap/types.go
  pkg/network/kube_proxy.go
  pkg/network/kube_proxy_test.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
Labels: lgtm, approved

#1209 SDN 2316: Use GatewayConfig in OVN-K to set gateway modes
  README.md
  bindata/network/ovn-kubernetes/004-config.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  hack/KIND_CNO.md
  hack/gateway-mode.yaml
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved

#1253 Bump openshift/build-machinery-go
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: lgtm, approved

#1236 OVN-K: Enable OVN metrics to be consumed by ServiceMonitor
  bindata/network/ovn-kubernetes/monitor.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved

#1249 Pod networking on DPU host in Infra and Tenant clusters
  bindata/network-diagnostics/network-check-target.yaml
  bindata/network/network-metrics/001-daemonset.yaml
Labels: lgtm, approved

#1237 OVN-K alerts: Fix incorrect metric name reference
  bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
Labels: lgtm, approved

#1256 Bug 2022144: sbdb and nbdb containers leave pid around if they restarted or crashed
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1112 Cloud network config controller - CNO deployment
  bindata/cloud-network-config-controller/000-ns.yaml
  bindata/cloud-network-config-controller/001-crd.yaml
  bindata/cloud-network-config-controller/002-rbac.yaml
  bindata/cloud-network-config-controller/003-credentialrequest.yaml
  bindata/cloud-network-config-controller/controller.yaml
  bindata/network/openshift-sdn/003-rbac-controller.yaml
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/004-config.yaml
  hack/update-codegen.sh
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
  pkg/bootstrap/types.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/cloud_network.go
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
Labels: lgtm, approved

#1241 Add MTU migration support for OVNKubernetes and OpenshiftSDN
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/004-config.yaml
  pkg/network/cluster_config.go
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
Labels: lgtm, approved

#1258 Bug 2033422: bootstrapOVNGatewayConfig should only be called once
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#1261 Bug 2034322: Move infrastructure bootstrap to its own package
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render.go
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/platform.go
  pkg/platform/platform_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1231 Bug 2034517: watch and apply changes of the ovs-flows-config configmap
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/bootstrap/types.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1262 Bug 2034398: Whereabouts CRD should include a "podref" field.
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
