Repository openshift/cluster-network-operator, pull requests merged in 2022-12, with the labels that each got.

#1586 Bug OCPBUGS-736: Kuryr: If set use MTU from Config for svc net
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#1647 The allowlist daemonset should set a priority class.
  bindata/allowlist/daemonset/daemonset.yaml
Labels: lgtm, approved

#1637 OCPBUGS-3916: SDN alerts: Add `$labels.node` to `SDNPodNotRady` metric
  bindata/network/openshift-sdn/alert-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1644 Support RHOBS monitoring for HyperShift
  bindata/network/multus-admission-controller/monitor.yaml
  bindata/network/ovn-kubernetes/managed/monitor-master.yaml
  pkg/network/multus_admission_controller.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved

#1650 Fix info log formatting
  pkg/controller/egress_router/egress_router_controller.go
  pkg/operator/operator.go
Labels: lgtm, approved

#1655 OCPBUGS-2532: Fix default disable-udp-aggregation value on s390x
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#1648 OCPBUGS-4350: Fix handling of deployment and statefulset updates
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/network/ovn_kubernetes.go
  pkg/render/render.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#1607 OCPBUGS-2947: Disable the drop-icmp container 'oc' pprof webserver on Azure
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical

#1660 [release-4.12] OCPBUGS-4686: Revert "Remove references to the hosts kubeconfig"
  cmd/cluster-network-operator/main.go
  hack/run-locally.sh
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical

#1641 [release-4.11] OCPBUGS-3490: OVN-Kubernetes: Prefer oldest nodes
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1669 Fix CNO crashing when Kuryr without MTU is set
  pkg/network/kuryr.go
Labels: lgtm, approved

#1670 update 'make install.tools' for golangci-lint
  Makefile
Labels: lgtm, approved
