Repository openshift/cluster-network-operator, pull requests merged in 2022-06, with the labels that each got.

#1463 Bug 2091167: incorrectly setting rbac role for certificatesigningrequests
  bindata/network/ovn-kubernetes/common/002-rbac.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1471 Bug 2092495: ovn: use up to 4 northd threads in non-SNO clusters
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1472 Bug 2073452: Copying CNI binaries should be an atomic operation.
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1455 Bug 2089805: Enable config duration for OVN-Kubernetes
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1461 Bug 2092047: cncc: add RBAC coordination.k8s.io leases
  bindata/cloud-network-config-controller/002-rbac.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1474 Bug 2090336: Multus should log at a verbose log level (without a logfile)
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1483 Bug 2095756: client: register types during init, not later
  pkg/client/client.go
  pkg/client/fake/fake_client.go
  pkg/operator/operator.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1479 Bug 2095772: bindata: managed: reduce memory requests to align with observed usage
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1481 Bug 2094071: Add southboundStale alert runbook
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1467 [release-4.10] Bug 2084591: Cleanup CNO relatedObjects
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#1496 Bug 2100079: Update sdn-controller perms for "configmapsleases" leaderelection
  bindata/network/openshift-sdn/003-rbac-controller.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1494 Bug 2084062: Make northd probe interval default to 10 seconds
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1497 remove @squeed from owners
  OWNERS
Labels: lgtm, approved, ok-to-test

#1438 Bug 2084366: ovn: try to gracefully terminate ovn-northd
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
