Repository openshift/cluster-network-operator, pull requests merged in 2022-02, with the labels that each got.

#1295 Fix bond cni source directory path
  bindata/network/multus/multus.yaml
Labels: lgtm, approved

#1266 Bug 2034355: Whereabouts IP Reconciliaton [backport 4.7]
  bindata/network/additional-networks/crd/001-crd.yaml
  bindata/network/multus/002-rbac.yaml
  bindata/network/multus/multus.yaml
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#1292 [release 4.6] Bug 2046551: add missing klog v2
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1299 Bug 2049613: Use a separate configmap for mtu migration config to avoid pod restart
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1293 Bug 2048793: Kuryr: Decrease vif_annotation_timeout
  bindata/network/kuryr/003-config.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1273 Bug 2038252: Backport 4.9 OVN drop icmp frag from other nodes on Azure cluster
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, qe-approved, backport-risk-assessed

#1267 Bug 2034358: Whereabouts IP Reconciliaton [backport 4.6]
  bindata/network/additional-networks/crd/001-crd.yaml
  bindata/network/multus/002-rbac.yaml
  bindata/network/multus/multus.yaml
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#1302 Bug 2048575: The Whereabouts ip-reconciler should use api-int load balancer
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1305 Bug 2051639: The Whereabouts ip-reconciler should use the internal load balancer and host network [backport 4.10]
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, staff-eng-approved

#1278 [release-4.8] Bug 2021221: ovnkube: set ovn-controller lflow cache limit to 1GB
  bindata/network/ovn-kubernetes/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#1309 Update project owners
  OWNERS
Labels: lgtm, approved

#1248 Bug 2010361: SDN alerts: conform to monitoring team style guide
  bindata/network/openshift-sdn/alert-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1257 Bug 2032559: Block DualStack migration for unsupported cluster types
  pkg/controller/clusterconfig/clusterconfig_controller.go
  pkg/controller/operconfig/cluster.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
  pkg/network/previous_test.go
  pkg/network/render.go
  pkg/network/render_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1228 [release-4.8] Bug 2023426: Add ip6tables NOTRACK rules for udp/6081
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#1311 Bug 2044227: Add rolling update strategy for Kuryr-CNI.
  bindata/network/kuryr/005-daemon.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1279 [release-4.9] Bug 2040530: ovn: try to gracefully terminate ovn-northd and ovsdb
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1312 Bug 1944264: ovnkube: gracefully terminate databases from preStop
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1315 ovn: stop spawning the ovn-nbctl daemon
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved

#1307 Bug 2037721: Do not apply OVN-Kubernetes `PodDisruptionBudget` on single-node clusters
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1318 Bug 2058671: ip reconciler: auto clean failed jobs
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1314 Fix group for CVO override used for running CNO locally
  hack/overrides-patch.yaml
Labels: lgtm, approved
