Repository openshift/cluster-network-operator, pull requests merged in 2022-01, with the labels that each got.

#1268 Bug 2035093: Cloud network config controller: Fix for Hypershift
  bindata/cloud-network-config-controller/controller.yaml
  pkg/network/render.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1272 Bug 2036861: multitenant - Add openshift-kube-apiserver-operator to global namespaces
  bindata/network/openshift-sdn/004-multitenant.yaml
  pkg/network/openshift_sdn_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1269 Bug 2018093: Kuryr: Add resource requests for pods
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/kuryr/006-controller.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1221 Bug 1943363: ovn: try to gracefully terminate ovn-northd
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1259 Bug 2034153: Fix MTU migration verification for OpenShiftSDN
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1275 Bug 2034460: cncc: handle advanced AWS and Azure configurations
  bindata/cloud-network-config-controller/003-configmaps.yaml
  bindata/cloud-network-config-controller/controller.yaml
  pkg/apply/apply.go
  pkg/bootstrap/types.go
  pkg/names/names.go
  pkg/network/cloud_network.go
  pkg/network/render.go
  pkg/platform/platform.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1229 Bug 2023423: Add ip6tables NOTRACK rules for udp/6081
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1277 BUG 2034413: cncc: create Cloud CredentialsRequest in /manifests
  bindata/cloud-network-config-controller/002-rbac.yaml
  bindata/cloud-network-config-controller/controller.yaml
  manifests/01-cncc-namespace.yaml
  manifests/02-cncc-credentials.yaml
  pkg/controller/operconfig/operconfig_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1084 Bug 1924839: [release-4.7] Update protobuf version to address CVE-2021-3121
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/event/core/event.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1246 Bug 2010663: OVN-K alerts: conform to monitoring team style guide
  bindata/network/ovn-kubernetes/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/alert-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1271 Bug 2037500: Bump openshift/build-machinery-go
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/admissionregistration.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1225 Bug 2022747: Allow to use proxy to connect to OSP cloud
  bindata/network/kuryr/003-config.yaml
  bindata/network/kuryr/006-controller.yaml
  go.mod
  pkg/bootstrap/types.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1283 Bug 2041329: cncc: add serviceAccountNames to CredentialsRequests
  manifests/02-cncc-credentials.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1285 Bug 2038732: Add egress* patch credentials for ovnkube-master
  bindata/network/ovn-kubernetes/003-rbac-controller.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1128 Bug 1896533: Nonexistent Namespaces Degradation logging message
  pkg/controller/operconfig/operconfig_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1251 Bug 2035459: modify cluster-network-features for OpenshiftSDN
  bindata/network/openshift-sdn/cni-features.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, px-approved, qe-approved

#1280 Bug 2041989: no CredentialsRequests in ibm-cloud-managed
  manifests/0000_70_cluster-network-operator_01_credentialsrequest.yaml
  manifests/02-cncc-credentials.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1287 clean up OWNERS
  OWNERS
Labels: lgtm, approved, bugzilla/valid-bug

#1264 Bug 2034351: Whereabouts IP Reconciliaton [backport 4.9]
  bindata/network/additional-networks/crd/001-crd.yaml
  bindata/network/multus/002-rbac.yaml
  bindata/network/multus/multus.yaml
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#1250 Bug 2039321: SDN: Expose controller metrics for collection
  bindata/network/openshift-sdn/003-rbac-controller.yaml
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/monitor.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1254 Bug 2034155: Adds back --disable-snat-multiple-gws
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1276 Bug 2039345: Verify against mininimal IPv6 MTU value for clusters with IPv6 networks
  pkg/network/mtu.go
  pkg/network/openshift_sdn.go
  pkg/network/openshift_sdn_test.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1290 Bug 2042796: whereabouts, reconciler: disable retries on failure
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1265 Bug 2034352: Whereabouts IP Reconciliaton [backport 4.8]
  bindata/network/additional-networks/crd/001-crd.yaml
  bindata/network/multus/002-rbac.yaml
  bindata/network/multus/multus.yaml
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#1282 Bug 2041546: ovn-kubernetes: set RAFT election timer at RAFT cluster creation time
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
