Repository openshift/cluster-network-operator, pull requests merged in 2022-05, with the labels that each got.

#1401 Adds dougbtv to owners [release-4.10]
  OWNERS
Labels: lgtm, approved

#1404 Adds dougbtv to owners [release-4.7]
  OWNERS
Labels: lgtm, approved

#1405 Adds dougbtv to owners [release-4.6]
  OWNERS
Labels: lgtm, approved

#1403 Adds dougbtv to owners [release-4.8]
  OWNERS
Labels: lgtm, approved

#1402 Adds dougbtv to owners [release-4.9]
  OWNERS
Labels: lgtm, approved

#1390 Bug 2075475: Add default-route field to egress-router k8s.v1.cni.cncf.io/networks
  bindata/egress-router/001-deployment.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1412 ovn: reduce SB<->ovn-controller inactivity probe to 30 seconds
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: lgtm, approved

#1415 Hypershift: Copy all CNO conditions to HostedControlPlane status
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/status_manager.go
  pkg/network/hypershift.go
Labels: lgtm, approved

#1422 Add control-plane-component label to ovnkube-master for hypershift
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved

#1414 ovn: fix northd preStop command handling
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
Labels: lgtm, approved

#1411 add more sysctls to the multus allowlist
  bindata/network/multus/multus.yaml
Labels: lgtm, approved

#1420 Hypershift: Fix ovnkube-master priority class and set resource requests on token-minter
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved

#1421 Remove ObjectMeta.ClusterName usage
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/managed/005-service.yaml
  bindata/network/ovn-kubernetes/managed/007-certificate.yaml
  bindata/network/ovn-kubernetes/managed/008-route.yaml
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/managed/monitor-master.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  pkg/apply/apply.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/status_manager.go
  pkg/names/names.go
Labels: lgtm, approved

#1406 bindata/network-diagnostics, cloud-network-config-controller: comply to restricted pod security level
  bindata/cloud-network-config-controller/controller.yaml
  bindata/network-diagnostics/network-check-source.yaml
  bindata/network-diagnostics/network-check-target.yaml
Labels: lgtm, approved

#1419 Bug 2076877: Bump FlowScema apiVersion to v1beta2
  bindata/network/openshift-sdn/006-flowschema.yaml
  bindata/network/ovn-kubernetes/self-hosted/007-flowschema.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1367 Bug 2082611: Limit Kuryr pods permissions
  bindata/network/kuryr/001-rbac.yaml
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/kuryr/006-controller.yaml
  pkg/network/kuryr_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1428 Revert "ovn: reduce SB<->ovn-controller inactivity probe to 30 seconds"
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: lgtm, approved

#1425 Add gm metric record to use for telemetry exposure
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved

#1423 Hypershift: enable TLS for ovnkube-master metrics
  bindata/network/ovn-kubernetes/managed/monitor-master.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved

#1408 hypershift: add ovnkube-node-proxy container in ovnkube-node ds
  bindata/cloud-network-config-controller/controller.yaml
  bindata/network/mtu-prober/02-job.yaml
  bindata/network/multus/multus.yaml
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  pkg/bootstrap/types.go
  pkg/controller/operconfig/mtu_probe.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/cloud_network.go
  pkg/network/multus.go
  pkg/network/openshift_sdn.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/platform/platform.go
  pkg/platform/platform_test.go
Labels: lgtm, approved

#1416 Re-reconcile network on configmap, stop watching all configmaps in proxy controllers
  pkg/client/fake/fake_client.go
  pkg/client/types.go
  pkg/controller/configmap_ca_injector/controller.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/proxyconfig/controller.go
Labels: lgtm, approved

#1427 Bug 2079422: Bump PodDisruptionBudget to v1
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1432 Bug 2023295: Cleanup CNO relatedObjects
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1431 Bug 2086143: Status controller: use a label, rather than watching all objects
  pkg/controller/controller.go
  pkg/controller/operconfig/mtu_probe.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/operconfig/pod_controller.go
  pkg/controller/statusmanager/kube.go
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/pod_watcher.go
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/controller/statusmanager/testutil_test.go
  pkg/names/names.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1430 Bug 2086437: Enable EgressQoS controller
  bindata/network/ovn-kubernetes/common/001-crd.yaml
  bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1446 Bug 2086544: Stop passing hosted cluster token as a parameter to ovnkube-master
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1440 Bug 2087135: Fixing Hypershift nodeport flow
  bindata/network/ovn-kubernetes/managed/005-service.yaml
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1447 Bug 2086506: hypershift: respect statefulset when upgrading ovnk
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1448 Bug 2087556: Fix rendering DPU manifests
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1441 Bug 2086461: AWS: Use hardcoded MTU to speed up cluster creation
  pkg/controller/operconfig/mtu_probe.go
  pkg/controller/operconfig/mtu_probe_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1454 Bug 2086461: Hypershift: Also add default for Azure mtu
  pkg/controller/operconfig/mtu_probe.go
  pkg/controller/operconfig/mtu_probe_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1451 Bug 2087942: bump to go 1.18, lint improvements
  .ci-operator.yaml
  .golangci.yaml
  .golangciversion
  Dockerfile
  Dockerfile.rhel7
  go.mod
  hack/verify-style.sh
  pkg/controller/egress_router/egress_router_controller.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/network/cluster_config.go
  pkg/network/kube_proxy.go
  pkg/network/multus_ipam.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1325 Bug 2058675: ip-reconciler cronjob specification requires hostnetwork, api-int lb usage & proper backoff [backport 4.7]
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1450 Bug 2076776: remove patch permissions from ovnkube-node service account
  bindata/network/ovn-kubernetes/common/002-rbac.yaml
Labels: lgtm, approved, bugzilla/valid-bug

#1462 Bug 2073452: Copying CNI binaries should be an atomic operation.
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1410 Bug 2078501: [release-4.10] Drop Node update permission for sdn-node
  bindata/network/openshift-sdn/002-rbac.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
