Repository openshift/cluster-network-operator, pull requests merged in 2022-09, with the labels that each got.

#1546 Multus admission controller: Wait for token in Hypershift
  bindata/network/multus-admission-controller/admission-controller.yaml
Labels: lgtm, approved

#1492 Bug OCPBUGS-917: Add EgressQoS DstCIDR format validation
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved, jira/valid-bug

#1508 Bug 1894268: Allow users to specify ovnkube join subnet
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1544 OKD-49: Adds support for scos to multus
  bindata/network/multus/multus.yaml
Labels: lgtm, approved

#1518 Add vSphere platform to allow dual-stack cluster
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
  pkg/network/render.go
  pkg/network/render_test.go
Labels: lgtm, approved

#1548 SDN-3432: Add alert for OVNKubernetesControllerDisconnectedSouthboundDatabase
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
Labels: lgtm, approved

#1526 OVN-K alerts: first tranche
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved

#1541 Bug SDN-3458: HyperShift: Differentiate resources deployed by different CNO instances in status manager
  pkg/bootstrap/types.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/pod_watcher.go
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/names/names.go
  pkg/operator/operator.go
  pkg/platform/platform.go
Labels: lgtm, approved

#1519 Add controller to synchronize the API and Ingress VIP fields
  pkg/apply/apply.go
  pkg/controller/add_networkconfig.go
  pkg/controller/infrastructureconfig/OWNERS
  pkg/controller/infrastructureconfig/infrastructureconfig_controller.go
  pkg/controller/infrastructureconfig/predicates.go
  pkg/controller/infrastructureconfig/sync_vips.go
  pkg/controller/infrastructureconfig/sync_vips_test.go
  pkg/controller/statusmanager/status_manager.go
  pkg/names/names.go
Labels: lgtm, approved

#1554 OVN-K: add patch/update service permissions to controller
  bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
Labels: lgtm, approved

#1543 Migrate Multicast configuration during SDN migration and rollback
  pkg/client/list_pager.go
  pkg/controller/operconfig/migration.go
  pkg/controller/operconfig/migration_test.go
  pkg/controller/operconfig/mtu_probe_test.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/operconfig/test_helpers.go
Labels: lgtm, approved

#1556 Add ovn-kubernetes-microshift to image-stream
  manifests/image-references
Labels: lgtm, approved

#1552 microshift: update ovnk manifests
  bindata/network/ovn-kubernetes/microshift/configmap.yaml
  bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml
Labels: lgtm, approved

#1558 Allow empty vSphere status field in VIP sync
  pkg/controller/infrastructureconfig/sync_vips.go
  pkg/controller/infrastructureconfig/sync_vips_test.go
Labels: lgtm, approved

#1536 Migrate Egress IP configuration during SDN migration and rollback
  pkg/client/list_pager.go
  pkg/controller/operconfig/migration.go
  pkg/controller/operconfig/migration_test.go
  pkg/controller/operconfig/operconfig_controller.go
Labels: lgtm, approved

#1545 Bug: OCPBUGS-736: Kuryr: Use machine net MTU to create service net
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/networking.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#1561 OCPBUGS-1515: Use custom uint128 type when validating v6InternalSubnet
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#1555 [release-11] Bug OCPBUGS-1075: HyperShift: Differentiate resources deployed by different CNO instances
  pkg/bootstrap/types.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/pod_watcher.go
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/names/names.go
  pkg/operator/operator.go
  pkg/platform/platform.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1568 egress_ip: remove redundant config
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: lgtm, approved

#1570 OCPBUGS-1038: Multus IPAM detection should honor conflists
  pkg/network/multus_ipam.go
  pkg/network/multus_ipam_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#1533 Pass enable-udp-aggregation=true to ovn-kubernetes
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved
