Repository openshift/cluster-network-operator, pull requests merged in 2022-08, with the labels that each got.

#1524 Bug 2116982: multus-admission-controller SNO number of replicas
  bindata/network/multus-admission-controller/admission-controller.yaml
  pkg/bootstrap/types.go
  pkg/controller/operconfig/mtu_probe.go
  pkg/controller/operconfig/mtu_probe_test.go
  pkg/network/cloud_network.go
  pkg/network/kuryr.go
  pkg/network/multus_admission_controller.go
  pkg/network/multus_admission_controller_test.go
  pkg/network/openshift_sdn.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render.go
  pkg/network/render_test.go
  pkg/network/testutil_test.go
  pkg/platform/platform.go
  pkg/platform/platform_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1517 Add microshift ovnk manifests
  bindata/network/ovn-kubernetes/microshift/clusterrole.yaml
  bindata/network/ovn-kubernetes/microshift/clusterrolebinding.yaml
  bindata/network/ovn-kubernetes/microshift/configmap.yaml
  bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml
  bindata/network/ovn-kubernetes/microshift/master/serviceaccount.yaml
  bindata/network/ovn-kubernetes/microshift/namespace.yaml
  bindata/network/ovn-kubernetes/microshift/node/daemonset.yaml
  bindata/network/ovn-kubernetes/microshift/node/serviceaccount.yaml
  bindata/network/ovn-kubernetes/microshift/role.yaml
  bindata/network/ovn-kubernetes/microshift/rolebinding.yaml
Labels: lgtm, approved

#1477 [release-4.10] Bug 2095111: ovn: fix northd preStop command handling
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1521 Render CRDs for both OSDN and OVNK during migration
  pkg/network/render.go
Labels: lgtm, approved

#1527 Bug 2103680: avoid overrriding disableNetworkDiagnostics on reconciliation
  pkg/apply/apply.go
  pkg/apply/merge.go
  pkg/apply/merge_test.go
  pkg/client/fake/fake_client.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1523 Add missing runbook links for OVN-kubernetes alerts
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved

#1528 Bug OCPBUGS-216: Kuryr: Bump timeoutSeconds for livenessProbe
  bindata/network/kuryr/006-controller.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#1525 HyperShift: Move CNCC to the controll-plane namespace
  bindata/cloud-network-config-controller/common/001-crd.yaml
  bindata/cloud-network-config-controller/common/002-rbac.yaml
  bindata/cloud-network-config-controller/managed/003-configmaps.yaml
  bindata/cloud-network-config-controller/managed/controller.yaml
  bindata/cloud-network-config-controller/self-hosted/003-configmaps.yaml
  bindata/cloud-network-config-controller/self-hosted/controller.yaml
  pkg/network/cloud_network.go
  pkg/network/render.go
Labels: lgtm, approved

#1516 Multus admission controller changes for hypershift
  bindata/network/multus-admission-controller/001-service.yaml
  bindata/network/multus-admission-controller/002-rbac.yaml
  bindata/network/multus-admission-controller/003-webhook.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/multus-admission-controller/monitor.yaml
  bindata/network/multus-admission-controller/rules.yaml
  cmd/cluster-network-operator/main.go
  pkg/client/client.go
  pkg/client/fake/fake_client.go
  pkg/controller/statusmanager/pod_watcher.go
  pkg/controller/statusmanager/status_manager.go
  pkg/names/names.go
  pkg/network/cloud_network.go
  pkg/network/multus_admission_controller.go
  pkg/network/multus_admission_controller_test.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render.go
Labels: lgtm, approved

#1531 Hypershift: Allow configuring hostname and labels on the route
  bindata/network/ovn-kubernetes/managed/008-route.yaml
  pkg/bootstrap/types.go
  pkg/network/hypershift.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved

#1537 microshift: compact ovn databases periodically
  bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml
Labels: lgtm, approved

#1538 hypershift: set multus controller priority appropriate for hosted clusters
  bindata/network/multus-admission-controller/admission-controller.yaml
Labels: lgtm, approved

#1534 Migrate Egress Firewall Configuration during SDN migration and Rollback
  go.mod
  go.sum
  hack/update-codegen.sh
  manifests/0000_70_cluster-network-operator_01_crd.yaml
  manifests/0000_70_cluster-network-operator_01_egr_crd.yaml
  manifests/0000_70_cluster-network-operator_01_pki_crd.yaml
  pkg/controller/operconfig/migration.go
  pkg/controller/operconfig/operconfig_controller.go
  vendor/github.com/openshift/api/.ci-operator.yaml
  vendor/github.com/openshift/api/.gitignore
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_image_digest_mirror_set.go
  vendor/github.com/openshift/api/config/v1/types_image_tag_mirror_set.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/types_project_helm_chart_repository.go
  vendor/github.com/openshift/api/helm/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/howqq
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  vendor/github.com/openshift/api/monitoring/v1alpha1/types.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/networkoperator/v1/types_egressrouter.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_insights-operator_00-insightsoperator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_insights.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml-patch
  vendor/github.com/openshift/api/route/v1/test-route-validation.sh
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved

#1540 Use fixed name for creating EgressFirewall CRs
  pkg/controller/operconfig/migration.go
Labels: lgtm, approved
