Repository openshift/cluster-network-operator, pull requests merged in 2022-10, with the labels that each got.

#1564 OCPBUGS-1083: Move OVNK alert level to info
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1566 OCPBUGS-1341: Set owner reference for pod network connectivity check
  pkg/controller/connectivitycheck/connectivity_check_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#1573 Add sysctl whitelist controller
  bindata/allowlist/config/configmap.yaml
  bindata/allowlist/daemonset/daemonset.yaml
  bindata/network/multus/004-sysctl-configmap.yaml
  bindata/network/multus/multus.yaml
  pkg/controller/add_networkconfig.go
  pkg/controller/allowlist/allowlist_controller.go
  pkg/names/names.go
  pkg/network/multus.go
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved

#1588 Bug OCPBUGS-2328: Fix for index out of range error
  pkg/controller/allowlist/allowlist_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1583 SDN-3515: HyperShift: multus admission controller: expose metrics over HTTPs
  bindata/network/multus-admission-controller/001-service.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/multus-admission-controller/monitor.yaml
  pkg/network/multus_admission_controller.go
Labels: lgtm, approved

#1478 [release-4.9] Bug 2095112: ovn: fix northd preStop command handling
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1563 [release-4.10] OCPBUGS-1538: Make northd probe interval default to 10 seconds
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical

#1584 SDN-2591: allow hybrid overlay to be enabled post install
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved

#1590 Remove the allow_ra sysctl for ipv4 from default systl whitelist
  bindata/network/multus/004-sysctl-configmap.yaml
Labels: lgtm, approved

#1576 Jira OCPBUGS-1736: Always set PROXY variables for CNCC
  pkg/controller/operconfig/mtu_probe.go
  pkg/network/cluster_config_test.go
  pkg/network/multus.go
  pkg/network/openshift_sdn.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render_test.go
  pkg/network/testutil_test.go
  pkg/platform/platform.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#1597 fixed typo in comment
  bindata/network/multus/multus.yaml
Labels: lgtm, approved

#1599 Bug 2111588: Enable OVS metrics for ovnk
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1579 OCPBUGS-2362: Prefer oldest nodes, harden new alerts and revert setting new OVN-K alerts to info
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-low, jira/valid-bug

#1600 Bug 1896533: moved SetDegraded call out of object loop to process all items first
  pkg/controller/operconfig/operconfig_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
