Repository openshift/cluster-network-operator, pull requests merged in 2022-04, with the labels that each got.

#1365 Bug 2058368: move enable memory trimming to readiness prob
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1347 Add tuning cni sysctl allowlist to nodes
  bindata/network/multus/multus.yaml
Labels: lgtm, approved

#1345 Add statefulset in status manager
  pkg/client/client.go
  pkg/client/fake/fake_client.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/operconfig/pod_controller.go
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/names/names.go
  pkg/network/hypershift.go
  pkg/network/ovn_kubernetes.go
  pkg/operator/operator.go
Labels: lgtm, approved

#1356 Add ipsec daemonset for hypershift managed cluster
  bindata/network/ovn-kubernetes/common/ipsec.yaml
Labels: lgtm, approved

#1358 Add ibm-cloud-managed annotations to 02-cncc-credentials.yaml, this is required in HyperShift
  manifests/02-cncc-credentials.yaml
Labels: lgtm, approved

#1361 Run ovnkube-master statefulset pods in parallel
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved

#1375 Exclude openshift-kube-apiserver and openshift-apiserver service/endpoints from connectivity checks in hypershift
  pkg/controller/connectivitycheck/connectivity_check_controller.go
Labels: lgtm, approved

#1364 HyperShift: Watch StatefulSets in the management cluster
  pkg/controller/operconfig/operconfig_controller.go
Labels: lgtm, approved

#1370 Use the hosted cluster token explicitly
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved

#1376 Use (un)setProgressing for pod status update
  pkg/controller/statusmanager/pod_status.go
Labels: lgtm, approved

#1374 hypershift: enable ovnk-master metrics in management cluster
  bindata/network/ovn-kubernetes/common/monitor-node.yaml
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/managed/monitor-master.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/monitor-master.yaml
  pkg/bootstrap/types.go
  pkg/network/hypershift.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved

#1379 Don't return err with empty relatedClusterObject annotation
  pkg/controller/statusmanager/status_manager.go
Labels: lgtm, approved

#1359 Bug 2070047: Bump max value of hist quantile for kuryr_cni_request_duration
  bindata/network/kuryr/alert-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1372 hypershift: enable publishNotReadyAddress explicitly for ovnk-master service
  bindata/network/ovn-kubernetes/managed/005-service.yaml
  bindata/network/ovn-kubernetes/managed/008-route.yaml
  bindata/network/ovn-kubernetes/managed/monitor-master.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved

#1382 hypershift: disable TLS for ovnk master metrics
  bindata/network/ovn-kubernetes/managed/monitor-master.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved

#1360 Bug 1983056: Kuryr: Update CRD from upstream
  bindata/network/kuryr/002-crds.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1323 Bug 2058673: ip-reconciler cronjob specification requires hostnetwork, api-int lb usage & proper backoff [backport 4.9]
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1381 Proxyconfig: Add a knob for Hypershift to enable proxying internal apiserver address
  pkg/util/proxyconfig/no_proxy.go
  pkg/util/proxyconfig/no_proxy_test.go
Labels: lgtm, approved

#1349 Hypershift: Respect publishing strategy of OVN southbound database service
  bindata/network/ovn-kubernetes/managed/005-service.yaml
  bindata/network/ovn-kubernetes/managed/008-route.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved

#1368 OVN: remove detecing db_ip via kapi
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved

#1366 add runbook link for NodeWithoutOVNKubeNodePodRunning and V4SubnetAll…
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved

#1340 Multus: split pod/status rbac
  bindata/network/multus-admission-controller/002-rbac.yaml
  bindata/network/multus/002-rbac.yaml
Labels: lgtm, approved

#1378 Bug 2072766: Reserve port TCP/9104 for cluster-network-operator
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1385 hypershift: get control plane replicas from hcp
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved

#1386 Bug 2072710: Make northd probe interval default to 10 seconds
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1274 Bug 2038295: Backport 4.8 OVN drop icmp frag from other nodes on Azure cluster
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1328 raise the alert NoOvnMasterLeader to critical and add the runbook url
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved

#1363 Remove Kuryr mutating DNS webhook
  bindata/network/kuryr/007-service.yaml
  bindata/network/kuryr/008-admission.secret.yaml
  bindata/network/kuryr/009-webhook.secret.yaml
  bindata/network/kuryr/010-admission-controller.yaml
  bindata/network/kuryr/011-webhook.yaml
  pkg/bootstrap/types.go
  pkg/names/names.go
  pkg/network/kuryr.go
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/util/cert/cert.go
Labels: lgtm, approved

#1327 OVN-K alert: Increase severity and add runbook_url for NoRunningOvnMa…
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved

#1350 Bug 2063123: Drop Node update permission for sdn-node
  bindata/network/openshift-sdn/002-rbac.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1324 Bug 2058674: ip-reconciler cronjob specification requires hostnetwork, api-int lb usage & proper backoff [backport 4.8]
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1394 ovn-kube hypershift: fix pipefailure that prevents HA startup
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved

#1369 Bug 2072215: Make the use of the ip-reconciler cronjob opt-in by detecting IPAM type usage
  bindata/network/multus/multus.yaml
  pkg/network/multus.go
  pkg/network/multus_ipam.go
  pkg/network/multus_ipam_test.go
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1397 Adds dougbtv to owners as approver and reviewer
  OWNERS
Labels: lgtm, approved

#1396 Bug 2078910: Correct runbook_url field location within schema
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1393 ovnkube: export OVS metrics along with OVN metrics
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved

#1384 Revert "Revert ipsec: Allow enablement/disablement at runtime"
  README.md
  bindata/network/ovn-kubernetes/common/ipsec.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, ok-to-test

#1395 Bug 2071859: Switch dnsPolicy to Default for OVN hostNetwork pods
  bindata/network/ovn-kubernetes/common/error-cni.yaml
  bindata/network/ovn-kubernetes/common/ipsec.yaml
  bindata/network/ovn-kubernetes/common/pre-puller.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1409 Bug 2080255: SDN: Re-add list/watch/get permissions for nodes needed for EgressIP
  bindata/network/openshift-sdn/002-rbac.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1392 OCPVE-106 Customize rollout strategy to fix SNO upgrade
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: lgtm, approved
