Repository openshift/cluster-network-operator, pull requests merged in 2022-07, with the labels that each got.

#1468 [release-4.9] Bug 2092265: Cleanup CNO relatedObjects
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#1503 Bug 2103590: Add init container to ensure that Status.podIP is set before postStart hooks run
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1491 Bug 2060079: Enhance sensitivity of SDN alert NodeProxyApplySlow
  bindata/network/openshift-sdn/alert-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1498 Bug 2100601: Update CNO to config EgressIP timeout for ovnk
  README.md
  bindata/cloud-network-config-controller/001-crd.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  go.mod
  go.sum
  manifests/0000_70_cluster-network-operator_01_crd.yaml
  manifests/0000_70_cluster-network-operator_01_pki_crd.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1510 Bug 2108232: Revert "Bug 2085089: Pass enable-udp-aggregation=true to ovn-kubernetes"
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1513 Bug 2108236: Revert "Bug 2085089: Pass enable-udp-aggregation=true to ovn-kubernetes"
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved

#1514 The Multus admission controller should run as a deployment
  bindata/network/multus-admission-controller/admission-controller.yaml
  pkg/network/multus_admission_controller_test.go
Labels: lgtm, approved

#1511 Add configmap list/watch rights to cloud-network-config-controller
  bindata/cloud-network-config-controller/002-rbac.yaml
Labels: lgtm, approved

#1469 [release-4.8] Bug 2092264: Cleanup CNO relatedObjects
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1443 multi-networkpolicy: Enable on SR-IOV networks
  bindata/network/multus-networkpolicy/multus-networkpolicy.yaml
Labels: lgtm, approved

#1435 Bug 2083266: Limit Kuryr pods permissions
  bindata/network/kuryr/001-rbac.yaml
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/kuryr/006-controller.yaml
  bindata/network/kuryr/010-admission-controller.yaml
  pkg/network/kuryr_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
