Repository openshift/cluster-network-operator, pull requests merged in 2023-01, with the labels that each got.

#1639 Allow SDN migration from Kuryr to OVNKubernetes
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/render.go
Labels: lgtm, approved

#1675 OCPBUGS-5306: OVN-Kubernetes: Stop sorting master node addresses
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical

#1470 [release-4.10] Bug 2092193: Bump PodDisruptionBudget to v1
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#1673 OCPBUGS-5306: ovn-kubernetes: ignore NB/SB readiness checks and dbchecker when not RAFT member
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical

#1682 [release-4.10] OCPBUGS-5575: CVE-2021-4238 goutils: RandomAlphaNumeric and CryptoRandomAlphaNumeric are not as random as they should be
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1502 Bug 2101918: Make the use of the ip-reconciler cronjob opt-in [backport 4.8]
  bindata/network/multus/multus.yaml
  pkg/network/multus.go
  pkg/network/multus_ipam.go
  pkg/network/multus_ipam_test.go
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#1683 [release-4.9] OCPBUGS-5574: CVE-2021-4238 goutils: RandomAlphaNumeric and CryptoRandomAlphaNumeric are not as random as they should be
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1665 OCPBUGS-3272: Unhealthy Readiness Probe failing ci
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1587 OCPBUGS-6736: Remove nbctl logfile
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1615 OCPBUGS-3461: CNI binary copy should account for the possibility of symlinks [backport 4.12]
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical

#1684 [release-4.8] OCPBUGS-5573: CVE-2021-4238 goutils: RandomAlphaNumericand CryptoRandomAlphaNumeric are not as random as they should be
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1676 ovn-kubernetes: Allow node_mgmt_port_netdev_flags for non-DPU modes
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, ok-to-test
