Repository openshift/cluster-network-operator, pull requests merged in 2023-03, with the labels that each got.

#1720 Enables nodeSelector to be used in egress firewall rule
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved

#1707 Allow cidr expansion
  pkg/names/names.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render.go
  pkg/network/render_test.go
Labels: lgtm, approved

#1716 SDN-3730: OVN IC: migrate master alerts to cluster manager
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved, jira/valid-reference

#1630 SDN-3597: OVN-K alerts: add OVS overflow alerts
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
Labels: lgtm, approved, jira/valid-reference

#1710 Remove the ovn-kind-cno.sh script
  hack/KIND_CNO.md
  hack/ovn-kind-cno.sh
Labels: lgtm, approved

#1709 use annotation on the daemonset to update hybrid overlay
  pkg/names/names.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved

#1728 OCPBUGS-8692: HyperShift: Set affinity, tolerations and co-location for all hcp resources created by CNO
  bindata/cloud-network-config-controller/managed/controller.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1715 OCPBUGS-9931: Enable configuration of node healthz server on ovnkube
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1725 add/update some UTs around clusternetwork change
  pkg/network/render_test.go
Labels: lgtm, approved

#1693 Whereabouts should implement the reconciliation controller
  bindata/network/multus/multus.yaml
  pkg/network/multus_ipam_test.go
Labels: lgtm, approved

#1730 [release-4.13] OCPBUGS-9926: Enable configuration of node healthz server on ovnkube
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1727 OCPBUGS-8707: Point libreswan to proper nss location
  bindata/network/ovn-kubernetes/common/ipsec.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1687 OCPBUGS-5955: Backport Added missing API field podref to OverlappingRangeIPReservation CRD
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1668 Set OVN-K north/south bound stale alerts severity to critical
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved

#1742 [release-4.11] OCPBUGS-10487: Enable configuration of node healthz server on ovnkube
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1617 OCPBUGS-64: CNI binary copy should account for the possibility of symlinks [backport 4.10]
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1748 OCPBUGS-10649: HyperShift: Add POD_NAME env to ovnkube-node
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1747 ovn-kube: move back to unsuffixed RHEL9 images
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
Labels: lgtm, approved

#1735 Fix tier label, privileged, HOSTNAME/NODENAME in whereabouts reconciler
  bindata/network/multus/002-rbac.yaml
  bindata/network/multus/multus.yaml
Labels: lgtm, approved

#1760 OCPBUGS-7777: use --template instead of -a for 'oc observe'
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1553 SDN-3444: Add runbook url for SBDB connectivity alert
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
Labels: lgtm, approved
