Repository openshift/cluster-network-operator, pull requests merged in 2023-11, with the labels that each got.

#2100 OCPBUGS-23082: set automountServiceAccountToken to false for hypershift managed network-node-identity deploy
  bindata/network/node-identity/managed/node-identity.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#2093 [release-4.13]SDN-4184: Limit OVN-Kubernetes RBAC permissions
  bindata/network/ovn-kubernetes/common/002-rbac.yaml
  bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/common/ipsec.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2113 OCPBUGS-22869: hypershift, hosted clusters: enable multi-homing and multi-net features
  bindata/network/ovn-kubernetes/managed/common/004-config.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#2111 NO ISSUE: add ownership of the proxy-ca
  pkg/controller/configmap_ca_injector/controller.go
  pkg/controller/proxyconfig/controller.go
  pkg/names/names.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2096 OCPBUGS-23011: Block upgrades to 4.15 with Kuryr
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1871 NETOBSERV-1047: Add a cluster monitoring dashboard for ovn
  bindata/dashboards/configmaps.yaml
  pkg/controller/add_networkconfig.go
  pkg/controller/dashboards/dashboard_controller.go
  pkg/controller/dashboards/netstats.json
  pkg/controller/dashboards/ovn-health.json
  pkg/controller/statusmanager/status_manager.go
  pkg/names/names.go
Labels: lgtm, approved, jira/valid-reference
