Repository openshift/cluster-network-operator, pull requests merged in 2023-08, with the labels that each got.

#1893 OCPBUGS-15945: Stop using utilruntime.PanicHandlers to handle reconciliation panics
  pkg/controller/allowlist/allowlist_controller.go
  pkg/controller/clusterconfig/clusterconfig_controller.go
  pkg/controller/configmap_ca_injector/controller.go
  pkg/controller/egress_router/egress_router_controller.go
  pkg/controller/infrastructureconfig/infrastructureconfig_controller.go
  pkg/controller/ingressconfig/ingressconfig_controller.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/pki/pki_controller.go
  pkg/controller/proxyconfig/controller.go
  pkg/controller/signer/signer-controller.go
  pkg/controller/statusmanager/pod_watcher.go
  pkg/controller/statusmanager/status_manager.go
  pkg/operator/operator.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1697 Add OpenStack platform to list of allowed dual-stack clusters
  pkg/network/render.go
Labels: lgtm, approved

#1890 Bug 16136: change whereabouts ip reconciler exec
  bindata/network/multus/multus.yaml
Labels: lgtm, approved

#1919 Add jcaamano to top level OWNERS
  OWNERS
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1922 CCO-294: Switch azure credentials request to use explicit permissions
  manifests/02-cncc-credentials.yaml
Labels: lgtm, approved, jira/valid-reference

#1928 OVN-Kubernetes ipsec: create the CSR with a random name
  bindata/network/ovn-kubernetes/common/002-rbac.yaml
  bindata/network/ovn-kubernetes/common/ipsec.yaml
Labels: lgtm, approved

#1915 Multus thick plugin support
  bindata/network/multus/multus.yaml
  pkg/network/multus.go
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved

#1904 OCPBUGS-16019: prevent creation of multiple cni-sysctl-allowlist-ds pods
  pkg/controller/allowlist/allowlist_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1944 Add rolling update for managed ovnkube-control-plane
  bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-control-plane.yaml
Labels: lgtm, approved

#1934 Remove certificatesigningrequests/update permission from ovnkubenode
  bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
Labels: lgtm, approved

#1962 OCPBUGS-17964: ovn-k, managed: Align join subnet configuration
  bindata/network/ovn-kubernetes/managed/common/004-config.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1949 OCPBUGS-17677: [Azure] Add granular permission for assigning egressIP to NIC to Azure CredentialsRequest for workload identity.
  manifests/02-cncc-credentials.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1936 OCPBUGS-17457: prevent creation of multiple cni-sysctl-allowlist-ds pods
  pkg/controller/allowlist/allowlist_controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1935 OCPBUGS-17257: CVE-2023-3978: golang.org/x/net/html: Cross site scripting
  go.mod
  go.sum
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_loong64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/text/language/match.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1950 [release-4.13] OCPBUGS-17721: Enhance check controller to remove old check objects
  pkg/controller/connectivitycheck/connectivity_check_controller.go
  pkg/controller/connectivitycheck/connectivity_check_template.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1952 OCPBUGS-16051, OCPBUGS-3176: Enables IP Forwarding config in CNO
  bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1971 OCPBUGS-17782, SDN-3664: Join ovnkube-controller and ovnkube-node container for multizone setup
  bindata/network/ovn-kubernetes/common/monitor-node.yaml
  bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/util/util.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1953 OCPBUGS-18175: Fix bond-cni's default directory in multus manifest
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1948 OCPBUGS-17656: prevent creation of multiple cni-sysctl-allowlist-ds pods
  pkg/controller/allowlist/allowlist_controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1979 OCPBUGS-18363: Add '/etc/cni/multus/net.d' into volumemount in multus pod
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
