Repository openshift/cluster-network-operator, pull requests merged in 2023-06, with the labels that each got.

#1829 OCPBUGS-13067: Fix tier label, privileged, HOSTNAME/NODENAME in whereabouts reconciler [backport 4.12]
  bindata/network/multus/002-rbac.yaml
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1828 OCPBUGS-14384: Remove nodeSelector for architecture in whereabouts daemonset
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1834 OCPBUGS-14833: Fixes lint issues
  pkg/controller/proxyconfig/controller.go
  pkg/controller/signer/signer-controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1830 OCPBUGS-11882: Added another volume to safe-to-evict-local-volume annotation
  bindata/cloud-network-config-controller/managed/controller.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1835 OCPBUGS-14714: Do not rely on ControlPlaneTopology do determine if running in HyperShift
  bindata/network/multus-admission-controller/admission-controller.yaml
  pkg/controller/operconfig/mtu_probe.go
  pkg/controller/operconfig/mtu_probe_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#1755 CCO-358: Manifest changes necessary to support Azure Workload Identity
  bindata/cloud-network-config-controller/common/002-rbac.yaml
  bindata/cloud-network-config-controller/managed/controller.yaml
  bindata/cloud-network-config-controller/self-hosted/controller.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1841 OCPBUGS-15138: Add kubernetes.io/os nodeSelector to wherebouts reconciler DS
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1765 [SDN-2484] Add support for AdminPolicyBasedExternalRoute CRD and controller's RBAC
  bindata/network/ovn-kubernetes/common/001-crd.yaml
  bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
Labels: lgtm, approved

#1796 Add multi-networkpolicies support for OVN
  bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved

#1843 CCO-356: Add Infrastructures permission to CNCC cluster role
  bindata/cloud-network-config-controller/common/002-rbac.yaml
Labels: lgtm, approved, jira/valid-reference

#1851 OCPBUGS-15282: Add release version annotation to whereabouts-reconciler
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference
