Repository openshift/cluster-network-operator, pull requests merged in 2023-05, with the labels that each got.

#1794 [release-4.10] OCPBUGS-12795: remove TLS_RSA_WITH_AES_128_CBC_SHA256 cipher
  bindata/kube-proxy/kube-proxy.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/network-metrics/001-daemonset.yaml
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1788 OCPBUGS-11565: High API requests due to allowlist and operconfig reconcilers running too often
  pkg/controller/allowlist/allowlist_controller.go
  pkg/controller/operconfig/operconfig_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1721 OCPBUGS-12856: Support Device Plugin Resources For Smart NIC and DPU Hosts
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
  hack/dpu-mode.yaml
  hack/hardware-offload-config.yaml
  pkg/bootstrap/types.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/kube_proxy.go
  pkg/network/kube_proxy_test.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1786 OCPBUGS-5027: Make the operator degraded on panic
  go.mod
  go.sum
  pkg/controller/operconfig/cluster.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/pod_status.go
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/operator/operator.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/alias.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/lazyrestmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/register.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/types.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1803 OCPBUGS-13219: Use `IfNotPresent` instead of `Always` in OVNK upgrades pre-puller
  bindata/network/ovn-kubernetes/common/pre-puller.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1809 [release-4.10] OCPBUGS-343: Configure ignored namespaces into multus-admission-controller
  bindata/network/multus-admission-controller/admission-controller.yaml
  pkg/apis/network/v1/operatorpki_types.go
  pkg/client/client.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/multus_admission_controller.go
  pkg/network/multus_admission_controller_test.go
  pkg/network/render.go
  pkg/network/render_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1801 OCPBUGS-13067: Whereabouts should implement the reconciliation controller [backport 4.12]
  bindata/network/multus/multus.yaml
  pkg/network/multus_ipam_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1793 [release-4.13] OCPBUGS-11750: fix reconciliation process of the allowlist controller
  bindata/allowlist/daemonset/daemonset.yaml
  pkg/controller/allowlist/allowlist_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1752 OCPBUGS-10937: multus-admission-controller mounts secret with mode 0640
  bindata/network/multus-admission-controller/admission-controller.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1770 OCPBUGS-11448: add Hypershift release-image annotation to multus
  bindata/cloud-network-config-controller/managed/controller.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  pkg/bootstrap/types.go
  pkg/network/cloud_network.go
  pkg/network/multus_admission_controller.go
  pkg/network/ovn_kubernetes.go
  pkg/platform/hypershift.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference
