Repository openshift/cluster-network-operator, pull requests merged in 2023-10, with the labels that each got.

#2038 Revert Kuryr MTU fixes
  pkg/network/kuryr.go
  pkg/network/kuryr_test.go
  pkg/platform/openstack/kuryr_bootstrap.go
Labels: lgtm, approved

#2049 OCPBUGS-20076: Multus should determine kubeconfig path
  bindata/network/multus/multus.yaml
  pkg/network/multus.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2050 OCPBUGS-20064: Multus should determine kubeconfig path [backport 4.14]
  bindata/network/multus/multus.yaml
  pkg/network/multus.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2001 [release-4.13] OCPBUGS-19894: remove prestop hooks for northd, sbdbd and nbdb
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2051 OCPBUGS-20104: Don't run network node identity as root
  bindata/network/node-identity/common/001-node-identity-namespace.yaml
  bindata/network/node-identity/self-hosted/003-node-identity-scc-rbac.yaml
  bindata/network/node-identity/self-hosted/node-identity.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2054 OCPBUGS-20184: [release-4.14]: Don't run network node identity as root
  bindata/network/node-identity/common/001-node-identity-namespace.yaml
  bindata/network/node-identity/self-hosted/003-node-identity-scc-rbac.yaml
  bindata/network/node-identity/self-hosted/node-identity.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2056 Remove ability to deploy with Kuryr
  OWNERS_ALIASES
  README.md
  bindata/network/kuryr/000-ns.yaml
  bindata/network/kuryr/001-rbac.yaml
  bindata/network/kuryr/002-crds.yaml
  bindata/network/kuryr/003-config.yaml
  bindata/network/kuryr/003-credentials.yaml
  bindata/network/kuryr/004-user-ca-cert.yaml
  bindata/network/kuryr/005-daemon.yaml
  bindata/network/kuryr/006-controller.yaml
  bindata/network/kuryr/OWNERS
  bindata/network/kuryr/alert-rules.yaml
  bindata/network/kuryr/monitor.yaml
  docs/architecture.md
  docs/operands.md
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
  pkg/bootstrap/types.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/names/names.go
  pkg/network/bootstrap.go
  pkg/network/cluster_config.go
  pkg/network/kube_proxy.go
  pkg/network/kube_proxy_test.go
  pkg/network/kuryr.go
  pkg/network/kuryr_test.go
  pkg/network/render.go
  pkg/network/render_test.go
  pkg/platform/openstack/OWNERS
  pkg/platform/openstack/identity.go
  pkg/platform/openstack/kuryr_bootstrap.go
  pkg/platform/openstack/loadbalancer.go
  pkg/platform/openstack/networking.go
  pkg/util/ip/addr.go
  pkg/util/ip/addr_test.go
Labels: lgtm, approved

#2037 OCPBUGS-18089,OCPBUGS-18088: ovnkube: container scripts cleanup
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1989 OCPBUGS-18392: notify when /etc/openvswitch path changes
  bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-reference

#2058 Revert "Merge pull request #2037 from dcbw/db-script-cleanup"
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved

#2065 OCPBUGS-20519: hosted cluster upgrade failure from 4.13 stable to 4.14
  bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2063 [release-4.14] OCPBUGS-20472: hosted cluster upgrade failure from 4.13 stable to 4.14
  bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1929 [ovn-kubernetes] Make APB External Route namespace selector mandatory for a dynamic hop
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved

#1819 OCPBUGS-10652: ovnkube: disable conntrack on hybrid overlay VXLAN ports
  bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/single-zone-interconnect/ovnkube-node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2074 OCPBUGS-20533: Revisit cipher suits for multus-admission-controller's rbac-proxy
  bindata/network/multus-admission-controller/admission-controller.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1986 OCPBUGS-18569: hypershift: adjust backoff on infrastructure name retry
  pkg/operator/operator.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2010 multinetworkpolicy: allow Neighbor Discovery Protocol traffic
  bindata/network/multus-networkpolicy/custom-iptables-rules.yaml
  bindata/network/multus-networkpolicy/multus-networkpolicy.yaml
  pkg/network/multi_network_policy_test.go
Labels: lgtm, approved

#1795 OCPBUGS-15220: Add zone node preference to multus-admission-controller
  bindata/network/multus-admission-controller/admission-controller.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2048 OCPBUGS-19370: Added HCP label to CNO pods
  bindata/cloud-network-config-controller/managed/controller.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/node-identity/managed/node-identity.yaml
  bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-control-plane.yaml
  bindata/network/ovn-kubernetes/managed/single-zone-interconnect/ovnkube-master.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2047 OCPBUGS-18785: SDN controller manifest: add node name from downward kapi to sdn controller
  bindata/network/openshift-sdn/controller.yaml
Labels: lgtm, approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2077 OCPBUGS-15817: Egress router: request at least 100 milliCPU
  bindata/egress-router/001-deployment.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2052 [SDN-4071] two replicas for CM instead of 3
  bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-control-plane.yaml
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved

#2084 OCPBUGS-11179: change CNO to use custom ServiceAccount
  manifests/0000_70_cluster-network-operator_02_rbac.yaml
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2060 OCPBUGS-18089,OCPBUGS-18088: ovnkube: container scripts cleanup [v2]
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
