Repository openshift/cluster-network-operator, pull requests merged in 2023-07, with the labels that each got.

#1831 kube-proxy config overriding updates
  go.mod
  go.sum
  pkg/network/kube_proxy_test.go
  pkg/network/openshift_sdn_test.go
  pkg/util/k8s/kubeproxy.go
  pkg/util/k8s/kubeproxy_test.go
  vendor/k8s.io/kube-proxy/config/v1alpha1/types.go
  vendor/k8s.io/kube-proxy/config/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#1869 Change rhel7/8 to rhel8/9
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1867 OCPBUGS-15544: Add adminpolicybasedexternalroutes rights for ovnkube-node.
  bindata/network/ovn-kubernetes/common/002-rbac.yaml
  bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1877 OCPBUGS-15962: Add logic to pick the ovn-k8s-cni-overlay binary from the right dir
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1866 OCPBUGS-15794: fix: add missing annotation for workload partitioning
  bindata/allowlist/daemonset/daemonset.yaml
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1767 Edited multus-admission-controller deployment config to not add autom…
  bindata/network/multus-admission-controller/admission-controller.yaml
Labels: lgtm, approved

#1848 Enable EgressService controller
  bindata/network/ovn-kubernetes/common/001-crd.yaml
  bindata/network/ovn-kubernetes/common/002-rbac.yaml
  bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/microshift/clusterrole.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved

#1880 OCPBUGS-15977: Add logic to pick the openshift-sdn shims from right directories
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1870 Change rhel7/8 to rhel8/9
  bindata/network/multus/multus.yaml
Labels: lgtm, approved

#1903 OCPBUGS-15918: Skip rendering 0.0.0.0/0 for cluster proxy status
  pkg/util/proxyconfig/no_proxy.go
  pkg/util/proxyconfig/no_proxy_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1887 OCPBUGS-15544: Enable multi-external-gateway feature by default for managed and hosted clusters
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1912 ovn-k: Configure dns service namespace and name
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved

#1901 OCPBUGS-15961: FIPS related CNO changes
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1764 [release-4.12 ] OCPBUGS-11217:use annotation daemonset to update hybrid overlay
  pkg/names/names.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1907 [release-4.9] OCPBUGS-16312: pick the ovn-k8s-cni-overlay and openshift-sdn shims from right directories
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1891 OCPBUGS-16142: fix reconciliation process of the allowlist controller
  pkg/controller/allowlist/allowlist_controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1879 HOSTEDCP-1063: allow webhooks in hosted clusters to reach multus-admission-controller service
  bindata/network/multus-admission-controller/001-service.yaml
Labels: lgtm, approved, jira/valid-reference

#1916 [release-4.8] OCPBUGS-16685: pick the ovn-k8s-cni-overlay and openshift-sdn shims from right directories
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1917 [release-4.7] OCPBUGS-16686: pick the ovn-k8s-cni-overlay and openshift-sdn shims from right directories
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1918 [release-4.6] OCPBUGS-16687: pick the ovn-k8s-cni-overlay and openshift-sdn shims from right directories
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/ovnkube-node.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1923 [release-4.9] OCPBUGS-16894: Use pods oc vs host
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1924 [release-4.8] OCPBUGS-16872: Use pods oc vs host
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1926 [release-4.6] OCPBUGS-16893: Use pods oc vs host
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1925 [release-4.7] OCPBUGS-16891: Use pods oc vs host
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference
