Repository openshift/cluster-network-operator, pull requests merged in 2023-02, with the labels that each got.

#1691 [release-4.12] OCPBUGS-6494: OVN-Kubernetes: Stop sorting master node addresses, ignore readiness checks for redundant NB/SB
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1680 remove TLS_RSA_WITH_AES_128_CBC_SHA256 cipher
  bindata/kube-proxy/kube-proxy.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/network-metrics/001-daemonset.yaml
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved

#1694 OCPBUGS-6651: HyperShift: Do not use proxy for internal routes
  pkg/network/hypershift.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1692 OCPBUGS-6651: HyperShift: Add .hypershift.local to no proxy list
  pkg/util/proxyconfig/no_proxy.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1677 OCPBUGS-4417: Added missing API field podref to OverlappingRangeIPReservation CRD
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#1681 OCPBUGS-5842: Use pods oc vs host
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1713 Revert "OCPBUGS-5842: Use pods oc vs host"
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1699 ovn-k, multi-homing: enable the feature
  bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved

#1714 OCPBUGS-7354: Revert "Revert "OCPBUGS-5842: Use pods oc vs host""
  bindata/network/openshift-sdn/sdn.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1711 always create env.sh when run_vs_existing_cluster
  hack/run-locally.sh
Labels: lgtm, approved

#1672 OCPBUGS-5559: add default noProxy config for Azure
  pkg/util/proxyconfig/no_proxy.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug

#1717 Allow updates to pods
  bindata/network/ovn-kubernetes/common/002-rbac.yaml
  bindata/network/ovn-kubernetes/microshift/clusterrole.yaml
Labels: lgtm, approved

#1685 OCPBUGS-5953: Backport Added missing API field podref to OverlappingRangeIPReservation CRD [Backport 4.12]
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1718 Jira OCPBUGS-7774: Print RawCNIConfig in its string representation
  pkg/network/additional_networks.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1616 OCPBUGS-3462: CNI binary copy should account for the possibility of symlinks [backport 4.11]
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1633 OCPBUGS-4343: update apf configuration to use v1beta3
  bindata/network/openshift-sdn/006-flowschema.yaml
  bindata/network/ovn-kubernetes/self-hosted/007-flowschema.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1712 OCPBUGS-6730, SDN-3221: ovn-kubernetes: use RHEL9-based images
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
Labels: lgtm, approved, jira/valid-reference

#1674 Add ovnk alert for resource retry failure
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
Labels: lgtm, approved

#1686 OCPBUGS-5954: Backport Added missing API field podref to OverlappingRangeIPReservation CRD
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference
