Repository openshift/cluster-network-operator, pull requests merged in 2024-07, with the labels that each got.

#2379 OCPBUGS-32989: Add conditions for ignored-namespaces
  pkg/network/multus_admission_controller.go
  pkg/network/multus_admission_controller_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2427 [release-4.15] OCPBUGS-36367: update whereabouts crd
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2375 OCPBUGS-36499: [release-4.15] Bump Openshift API and backport configurable subnet knobs (transit / join / masquerade)
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml
  go.mod
  go.sum
  manifests/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
  manifests/0000_70_cluster-network-operator_01-Default.crd.yaml
  manifests/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
  manifests/0000_70_cluster-network-operator_01_pki_crd.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.network.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.network.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2368 OCPBUGS-30950: Set mount propagation to HostToContainer for /var/lib/kubelet
  bindata/network/multus/multus.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, ok-to-test, jira/valid-bug, jira/severity-important, jira/valid-reference

#2431 SDN-5029: ipam, virt: enable the persistent ips feature
  bindata/network/ovn-kubernetes/common/001-crd.yaml
  bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml
  manifests/0000_70_cluster-network-operator_01_pki_crd.yaml
  manifests/0000_70_network_01_networks.crd.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-reference

#2406 OCPBUGS-33758: Fix IC distributed control plane alerts
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#2434 [release-4.14] OCPBUGS-36722: update whereabouts crd
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2433 SDN-4934: Enable TechPreview FeatureGate for NetworkSegmentation
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2448 SDN-4919: OVN-Kubernetes UDN: EndpointSlice mirror controller RBAC permissions
  bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
Labels: lgtm, approved, jira/valid-reference

#2439 OCPBUGS-37205: Check every MachineConfigPool for IPsec plugin existence
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/platform/platform.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2441 CNV-43973: HCP custom tolerations integration
  bindata/cloud-network-config-controller/managed/controller.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/node-identity/managed/node-identity.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
  pkg/bootstrap/types.go
  pkg/hypershift/hypershift.go
  pkg/network/cloud_network.go
  pkg/network/multus_admission_controller.go
  pkg/network/node_identity.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, jira/valid-reference

#2420 [release-4.15] OCPBUGS-35837: Propogate hypershift control plane priority class override to multus and preserve container resource requests
  bindata/network/multus-admission-controller/admission-controller.yaml
  pkg/hypershift/hypershift.go
  pkg/network/multus_admission_controller.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, ok-to-test, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2451 OCPBUGS-37713: Handle random crictl errors in iptables-alerter
  bindata/network/iptables-alerter/002-script.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
