Repository openshift/cluster-network-operator, pull requests merged in 2024-03, with the labels that each got.

#2290 OCPBUGS-30150: ipsec: fix openssl typo
  bindata/network/ovn-kubernetes/common/ipsec.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2130 OPNET-358, OPNET-360: Allow VIP mutation in Infra CR
  pkg/controller/infrastructureconfig/infrastructureconfig_controller.go
  pkg/controller/infrastructureconfig/sync_specstatus.go
  pkg/controller/infrastructureconfig/sync_specstatus_test.go
  pkg/controller/infrastructureconfig/sync_vips.go
  pkg/controller/infrastructureconfig/sync_vips_test.go
  pkg/controller/infrastructureconfig/validations.go
  pkg/util/ip/addr.go
  pkg/util/ip/addr_test.go
Labels: lgtm, approved, jira/valid-reference

#2299 OCPBUGS-30299: Fix managed cluster detection on ARO
  pkg/platform/platform.go
  pkg/util/util.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2286 OCPBUGS-30021: [release-4.14] Disable network-node-identity on ROKS
  pkg/network/multus_admission_controller.go
  pkg/network/node_identity.go
  pkg/network/render.go
  pkg/network/render_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2106 OCPBUGS-22995: Tighten the permissions on whereabouts.conf
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#2320 [release-4.14] OCPBUGS-31360: Remove egressip write permissions from ovn-kubernetes-node
  bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2309 SDN-4607: Allow HyperShift ability to set ConfigMap through env var
  bindata/network/multus-admission-controller/001-service.yaml
  bindata/network/multus-admission-controller/monitor.yaml
  bindata/network/node-identity/managed/node-identity-service.yaml
  bindata/network/ovn-kubernetes/managed/monitor-control-plane.yaml
  pkg/bootstrap/types.go
  pkg/hypershift/hypershift.go
  pkg/network/multus_admission_controller.go
  pkg/network/multus_admission_controller_test.go
  pkg/network/node_identity.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render.go
  pkg/network/testutil_test.go
Labels: lgtm, approved, jira/valid-reference
