Repository openshift/cluster-network-operator, pull requests merged in 2024-09, with the labels that each got.

#2488 OCPBUGS-39398: Preload networking plugin locales
  bindata/networking-console-plugin/004-console-plugin.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2485 [release-4.15] NP-1064, OCPBUGS-39336: Remove managed cluster checking for live migration
  pkg/bootstrap/types.go
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
  pkg/network/render.go
  pkg/network/render_test.go
  pkg/platform/platform.go
  pkg/util/util.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2400 OCPBUGS-35417: Configure narrowing=yes for IPsec connections
  bindata/network/ovn-kubernetes/common/ipsec-host.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2502 [release-4.16] OCPBUGS-41840: Add configurable subnets while running hybrid-overlay-node binary
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2508 OCPBUGS-42238: Updates terminationGracePeriodSeconds to 30 seconds for Multus daemonset
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2507 HOSTEDCP-1981: Add controlplane cli image envar for use with hypershift
  pkg/network/cloud_network.go
  pkg/network/multus_admission_controller.go
  pkg/network/node_identity.go
Labels: lgtm, approved, jira/valid-reference

#2513 OCPBUGS-42472: Add certificatesigningrequests/watch RBAC to ovnkube-node
  bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference
