Repository openshift/cluster-network-operator, pull requests merged in 2024-04, with the labels that each got.

#2328 SDN-4596: Update (B)ANP CRDs; prepare for GA
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved, jira/valid-reference

#2314 [release-4.15] OCPBUGS-29654: Fully disable network-node-identity on ROKS
  pkg/network/node_identity.go
  pkg/platform/platform.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2306 OCPBUGS-26408: automountServiceAccountToken:false hosted CP pods
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2311 OCPBUGS-31669: [release-4.14] ensure local networking deployments within hypershift use the client side load balancer to be resilient to control plane node failures
  pkg/network/kube_proxy.go
  pkg/network/multus.go
  pkg/platform/platform.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2315 [release-4.14] OCPBUGS-30021: Fully disable network-node-identity on ROKS
  pkg/network/node_identity.go
  pkg/platform/platform.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2334 OCPBUGS-28230: enforce termination message policy on all platform pods
  bindata/network-diagnostics/network-check-target.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2340 OCPBUGS-28230: enforce termination message policy on all platform pods
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2095 OCPBUGS-22969: Use v1 for flowcontrol API
  bindata/network/openshift-sdn/006-flowschema.yaml
  bindata/network/ovn-kubernetes/self-hosted/007-flowschema.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2270 SDN-4163: Add ipsec state to telemetry
  bindata/cluster-network-operator/prometheus.yaml
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/ovn_kubernetes.go
  pkg/network/render.go
  pkg/util/ipsec/metrics.go
Labels: lgtm, approved, jira/valid-reference

#2341 OCPBUGS-32347: Improve IPsec MachineConfig readiness check
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2342 OCPBUGS-32402: Fix wait logic for IPsec certificate signing request
  bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml
  bindata/network/ovn-kubernetes/common/ipsec-host.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2346 SDN-4163: Improved prometheus rule for ipsec metric
  bindata/cluster-network-operator/prometheus.yaml
Labels: lgtm, approved, jira/valid-reference

#2327 OCPBUGS-31528: infraconfig: handle vSphere UPI by not updating any fields
  pkg/controller/infrastructureconfig/sync_specstatus.go
  pkg/controller/infrastructureconfig/sync_specstatus_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2329 SDN-4114: Add iptables-alerter daemonset
  bindata/network/iptables-alerter/001-rbac.yaml
  bindata/network/iptables-alerter/002-script.yaml
  bindata/network/iptables-alerter/003-daemonset.yaml
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
  pkg/bootstrap/types.go
  pkg/network/bootstrap.go
  pkg/network/render.go
Labels: lgtm, approved, jira/valid-reference

#2330 SDN-4726: Block upgrade for openshift-sdn
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
Labels: lgtm, approved, jira/valid-reference

#2356 Revert #2330 "SDN-4726: Block upgrade for openshift-sdn"
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
Labels: lgtm, approved, jira/valid-reference

#2361 SDN-4726: Reapply "Merge pull request #2330 from pperiyasamy/block-sdn-upgrade"
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
Labels: lgtm, approved, jira/valid-reference

#2362 OCPBUGS-33080: Update EQoS CRD to latest
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
