Repository openshift/cluster-network-operator, pull requests merged in 2024-10, with the labels that each got.

#2515 OCPBUGS-42449: Use CNIConfDir for mounting directory to ovn-ipsec-host pod
  bindata/network/ovn-kubernetes/common/ipsec-host.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2477 OCPBUGS-39300: rebase openshift/api for openshift-sdn removal [4.17]
  go.mod
  go.sum
  manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  manifests/0000_70_network_01_networks-Default.crd.yaml
  manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  manifests/0000_70_network_01_networks-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2526 NO-JIRA: OVN-Kubernetes node RBAC tightening
  bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
Labels: lgtm, approved, jira/valid-reference

#2462 SDN-5186: Process OVNObservability feature gate
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
Labels: lgtm, approved, jira/valid-reference

#2518 CNF-14257, CNF-14251: multi-networkpolicy: Enable for `ipvlan` and `bond` networkds
  bindata/network/multus-networkpolicy/multus-networkpolicy.yaml
Labels: lgtm, approved, jira/valid-reference

#2525 CNF-14199: Align FRR-K8s CRDs
  OWNERS
  OWNERS_ALIASES
  bindata/network/frr-k8s/001-crd.yaml
  bindata/network/frr-k8s/OWNERS
Labels: lgtm, approved, jira/valid-reference

#2531 CNF-13671: Adjust frr-k8s metrics
  bindata/network/frr-k8s/frr-k8s.yaml
  bindata/network/frr-k8s/monitor.yaml
  pkg/network/render_test.go
Labels: lgtm, approved, jira/valid-reference

#2535 CNF-14971: frr-k8s: allow setting the loglevel from env-overrides
  bindata/network/frr-k8s/frr-k8s.yaml
Labels: lgtm, approved, jira/valid-reference

#2532 OCPBUGS-42605: OCPBUGS-42244: Exporting environment varialbe NODE_CNI for live migration
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2522 HOSTEDCP-2035: Set up Azure authentication with cert for ARO HCP
  bindata/cloud-network-config-controller/managed/controller.yaml
  pkg/network/cloud_network.go
Labels: lgtm, approved, jira/valid-reference

#2517 NO-JIRA: onv-k, udn: Update UserDefinedNetwork CRD
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved, jira/valid-reference

#2545 OCPBUGS-39189: fix annotation from deployment to pod
  bindata/networking-console-plugin/002-deployment.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2546 OCPBUGS-43821: manifests/02-cncc-credentials: Set skipServiceCheck for GCP
  manifests/02-cncc-credentials.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
