Repository openshift/cluster-network-operator, pull requests merged in 2024-01, with the labels that each got.

#2069 SDN-4227: Use specific permissions for CNCC in GCP
  manifests/02-cncc-credentials.yaml
Labels: lgtm, approved, jira/valid-reference

#2163 [release-4.13] OCPBUGS-24570: Disable weak SSH cipher suitesRm weak ciphers 4.13
  bindata/kube-proxy/kube-proxy.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/network-metrics/001-daemonset.yaml
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2164 [release-4.12] OCPBUGS-24571: Disable weak SSH cipher suites
  bindata/kube-proxy/kube-proxy.yaml
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/network-metrics/001-daemonset.yaml
  bindata/network/openshift-sdn/controller.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-master.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2112 [release-4.14] OCPBUGS-24037: remove all managed fields used by old manager
  pkg/apply/apply.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2070 OCPBUGS-19635: OVN-K in SNO deployment mode: fix Lease override for CM
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2179 OCPBUGS-25760: Keep the live migration annotation consistant with the enhancement doc
  pkg/controller/clusterconfig/migration_test.go
  pkg/names/names.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#2169 OCPBUGS-25669: Update ovn-k managed control-plane RBAC
  bindata/network/ovn-kubernetes/common/003-rbac-controller.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/007-flowschema.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2173 OCPBUGS-25688: remove microshift folder, since CNO doesn't manage it
  bindata/network/ovn-kubernetes/microshift/clusterrole.yaml
  bindata/network/ovn-kubernetes/microshift/clusterrolebinding.yaml
  bindata/network/ovn-kubernetes/microshift/configmap.yaml
  bindata/network/ovn-kubernetes/microshift/master/daemonset.yaml
  bindata/network/ovn-kubernetes/microshift/master/serviceaccount.yaml
  bindata/network/ovn-kubernetes/microshift/namespace.yaml
  bindata/network/ovn-kubernetes/microshift/node/daemonset.yaml
  bindata/network/ovn-kubernetes/microshift/node/serviceaccount.yaml
  bindata/network/ovn-kubernetes/microshift/role.yaml
  bindata/network/ovn-kubernetes/microshift/rolebinding.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2094 [release-4.13] OCPBUGS-22293: remove all managed fields used by old manager
  pkg/apply/apply.go
  pkg/apply/fieldmanager.go
  vendor/k8s.io/client-go/util/csaupgrade/OWNERS
  vendor/k8s.io/client-go/util/csaupgrade/upgrade.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2187 OCPBUGS-25207: Render IPsec MachineConfig after cluster settles with MachineConfigs
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/platform/platform.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2153 OCPBUGS-24635: network node identity: tolarate all taints
  bindata/network/node-identity/self-hosted/node-identity.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2170 OCPBUGS-24379: Remove egressip write permissions from ovn-kubernetes-node
  bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2099 [release-4.12] OCPBUGS-24039: remove all managed fields used by old manager
  pkg/apply/apply.go
  pkg/apply/csaupgrade.go
  pkg/apply/fieldmanager.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2196 [release-4.14] OCPBUGS-24326: adminpolicybasedexternalroutes CR accepts an invalid IP address
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2199 NO-JIRA: Fix jira component info
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#2206 OCPBUGS-27264: Only reconcile on Node updates with Label changes
  pkg/controller/operconfig/operconfig_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2201 OCPBUGS-26952: Deploy CNO IPsec MC even if user already have one
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/platform/platform.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#1807 SDN-3708: Support configurable masquerade subnet in ovn-k
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-reference

#2209 OCPBUGS-26986: Add ConfigMap mount to the whereabouts-reconciler
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2204 OCPBUGS-27198: [release-4.15] Update ovn-k managed control-plane RBAC
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2214 OCPBUGS-27748: [release-4.15] Add ConfigMap mount to the whereabouts-reconciler
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2219 OCPBUGS-27858: [release-4.14] Add ConfigMap mount to the whereabouts-reconciler DaemonSet
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2213 OCPBUGS-27823: Not update migration conditions when any MCP is updating
  pkg/controller/clusterconfig/migration.go
  pkg/controller/operconfig/migration.go
  pkg/controller/operconfig/migration_test.go
  pkg/names/names.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2226 NO-JIRA: add kyrtapz as reviewer and approver
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#2208 OCPBUGS-25079: Prevent NoRunningOvnControlPlane alert getting fired continuously
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
Labels: lgtm, approved, ok-to-test, jira/valid-bug, jira/valid-reference

#2228 NO-JIRA: add kyrtapz as reviewer and approver for release 4.14
  OWNERS
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2229 NO-JIRA: add kyrtapz as reviewer and approver for release 4.13
  OWNERS
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2230 NO-JIRA: add kyrtapz as reviewer and approver for release 4.12
  OWNERS
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2234 OCPBUGS-19551: ovnkube: simplify northd threading and SNO templating
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
