Repository openshift/cluster-network-operator, pull requests merged in 2024-05, with the labels that each got.

#2364 OCPBUGS-28230: enforce termination message policy on all platform pods
  bindata/network/multus-networkpolicy/multus-networkpolicy.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2349 OCPBUGS-32525: Check every MachineConfigPool for IPsec plugin existence
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/platform/platform.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2273 OCPBUGS-29403: add more safe sysctls
  bindata/allowlist/config/configmap.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2365 USHIFT-2912: Add ref to MicroShift's Multus and CNI Plugins
  manifests/image-references
Labels: lgtm, approved, jira/valid-reference

#2360 OCPBUGS-32979: Update network operator status for IPsec
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2131 CFE-888: Enable DNSNameResolver feature-gate
  bindata/network/ovn-kubernetes/common/001-crd.yaml
  bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
  bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
  bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2371 OCPBUGS-33728: Add custom masquerade subnet against right key at ovnkube-config CM
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, ok-to-test, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#2344 NP-974: Validation for live migration from OpenShiftSDN to OVNKubernetes
  pkg/client/list_pager.go
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2358 OCPBUGS-32991: Add conditions for ignored-namespaces
  pkg/network/multus_admission_controller.go
  pkg/network/multus_admission_controller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2367 NP-975: Align new node subnet allocation between OVN-K and SDN during live migration
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, jira/valid-reference

#2382 OCPBUGS-34359: Ensure that the node-identity webhook address contains colons for IPv6
  bindata/network/node-identity/self-hosted/node-identity-pki.yaml
  bindata/network/node-identity/self-hosted/node-identity-webhook.yaml
  bindata/network/node-identity/self-hosted/node-identity.yaml
  pkg/network/node_identity.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2374 [release-4.16] OCPBUGS-34013: Add custom masquerade subnet against right key at ovnkube-config CM
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, ok-to-test, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2207 OCPBUGS-27925,OCPBUGS-30579:[release-4.14] tighten conditions for the state transitions in IC upgrade
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2377 OCPBUGS-33497: Handle pod exiting race conditions in iptables-alerter
  bindata/network/iptables-alerter/002-script.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2378 OCPBUGS-34214: Add conditions for ignored-namespaces
  pkg/network/multus_admission_controller.go
  pkg/network/multus_admission_controller_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
