Repository openshift/cluster-network-operator, pull requests merged in 2024-08, with the labels that each got.

#2380 OCPBUGS-32706: Add conditions for ignored-namespaces
  pkg/network/multus_admission_controller.go
  pkg/network/multus_admission_controller_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2453 OCPBUGS-37786: Add proxy env vars to onvkube-node
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2444 [release-4.14] OCPBUGS-37468: Backport ipsec state metric
  bindata/cluster-network-operator/prometheus.yaml
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/render.go
  pkg/util/ipsec/metrics.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2421 SDN-5070: Allow day 2 customization of masquerade subnet
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2461 OCPBUGS-37942: [release-4.12] update whereabouts crd
  bindata/network/additional-networks/crd/001-crd.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2455 NO-JIRA: more openshift-sdn cleanup
  README.md
  docs/architecture.md
  docs/operands.md
  hack/run-locally.sh
  pkg/network/bootstrap.go
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
  pkg/network/multi_network_policy_test.go
  pkg/network/multus_admission_controller_test.go
  pkg/network/multus_ipam_test.go
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
  sample-cluster-network-config.yaml
  sample-config.yaml
Labels: lgtm, approved, jira/valid-reference

#2465 SDN-4773: Add Azure MSI Env Var for ARO HCP
  bindata/cloud-network-config-controller/managed/controller.yaml
  pkg/network/cloud_network.go
Labels: lgtm, approved, jira/valid-reference

#2464 SDN-5144: Add UserDefinedNetwork CRD and RBAC
  bindata/network/ovn-kubernetes/common/001-crd.yaml
  bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2450 SDN-5072: Deploy FRR-K8s
  bindata/network/frr-k8s/000-ns.yaml
  bindata/network/frr-k8s/001-crd.yaml
  bindata/network/frr-k8s/002-rbac.yaml
  bindata/network/frr-k8s/config.yaml
  bindata/network/frr-k8s/frr-k8s.yaml
  bindata/network/frr-k8s/monitor.yaml
  bindata/network/frr-k8s/webhook.yaml
  go.mod
  go.sum
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
  pkg/controller/statusmanager/status_manager.go
  pkg/network/render.go
  pkg/network/render_test.go
  vendor/github.com/openshift/api/Dockerfile.ocp
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_console_01_consoles.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2460 SDN-4919: Change the masquerade subnet default value for new clusters
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
  pkg/bootstrap/types.go
  pkg/names/names.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, jira/valid-reference

#2466 OCPBUGS-38176: multus, Add openshift-cnv to globalNamespace
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2463 [release-4.14] OCPBUGS-38073: Fix IC distributed control plane alerts
  bindata/network/ovn-kubernetes/common/alert-rules.yaml
  bindata/network/ovn-kubernetes/managed/multi-zone-interconnect/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/multi-zone-interconnect/alert-rules-control-plane.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#2393 OCPBUGS-34613,OCPBUGS-34726,OCPBUGS-34727: Live migration backports
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
  pkg/client/list_pager.go
  pkg/controller/operconfig/cluster.go
  pkg/controller/operconfig/migration.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2468 OCPBUGS-38326: OVN-K, UDN CRD: Add missing permissions to control-plane
  bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, ok-to-test, jira/valid-bug, jira/severity-important, jira/valid-reference

#2471 OCPBUGS-38403: Add missing runbook for OVNKubernetesNorthdInactive
  bindata/network/ovn-kubernetes/managed/alert-rules-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/alert-rules-control-plane.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#2332 CONSOLE-3952: Add networking-console-plugin image to release payload
  manifests/0000_70_cluster-network-operator_03_deployment-ibm-cloud-managed.yaml
  manifests/0000_70_cluster-network-operator_03_deployment.yaml
  manifests/image-references
Labels: lgtm, approved, jira/valid-reference

#2404 NO-JIRA: iptables-alerter streamlining
  bindata/network/iptables-alerter/002-script.yaml
Labels: lgtm, approved, jira/valid-reference

#2322 CONSOLE-3952: Deploy networking-console-plugin by CNO
  bindata/networking-console-plugin/000-namespace.yaml
  bindata/networking-console-plugin/001-config-map.yaml
  bindata/networking-console-plugin/002-deployment.yaml
  bindata/networking-console-plugin/003-service.yaml
  bindata/networking-console-plugin/004-console-plugin.yaml
  pkg/bootstrap/types.go
  pkg/client/client.go
  pkg/client/fake/fake_client.go
  pkg/network/render.go
  pkg/platform/platform.go
Labels: lgtm, approved, jira/valid-reference

#2476 SDN-4900: rebase openshift/api for openshift-sdn removal
  go.mod
  go.sum
  manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  manifests/0000_70_network_01_networks-Default.crd.yaml
  manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  manifests/0000_70_network_01_networks-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/envtest-releases.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2482 OCPBUGS-39096: Live migration: report network overlap via live_migration_blocked metric
  pkg/network/cluster_config.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#2480 OCPBUGS-29497: HyperShift: do not use antiaffinity on single replica control planes
  bindata/network/multus-admission-controller/admission-controller.yaml
  bindata/network/node-identity/managed/node-identity.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2484 OCPBUGS-39189: add required-scc annotation to console-plugin deployment
  bindata/networking-console-plugin/002-deployment.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
