Repository openshift/cluster-network-operator, pull requests merged in 2025-05, with the labels that each got.

#2686 OCPBUGS-55488: Remove environment variables related to ARO HCP MIv2 for CNO
  bindata/cloud-network-config-controller/managed/controller.yaml
  pkg/network/cloud_network.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#2696 OCPBUGS-51093, OCPBUGS-55157: Pass '--gateway-mode' flag for ovnkube-cluster-manager
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2709 OCPBUGS-56051: Configure the terminationMessagePolicy for all containers deployed in HyperShift
  bindata/cloud-network-config-controller/managed/controller.yaml
  bindata/network/node-identity/managed/node-identity.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
