Repository openshift/cluster-network-operator, pull requests merged in 2025-02, with the labels that each got.

#2636 OCPBUGS-49621:Fix UDN and CUDN hostSubnet validation
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#2635 OCPBUGS-49670: OVNK should be able to annotate network ID on NADs
  bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2615 OCPBUGS-48312: frr-k8s: align manifests with operator
  bindata/network/frr-k8s/001-crd.yaml
  bindata/network/frr-k8s/frr-k8s.yaml
  bindata/network/frr-k8s/webhook.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2638 OCPBUGS-49746: ovn-k,cudn crd: Ensure matching toplogy and topology-config
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2628 SDN-5330: Keep rendering OVN IPsec when its daemonset not available
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2645 OCPBUGS-50625: Cherry-pick RouteAdvertisements support back to 4.18
  bindata/network/ovn-kubernetes/common/001-crd.yaml
  bindata/network/ovn-kubernetes/common/002-rbac-node.yaml
  bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml
  pkg/controller/statusmanager/status_manager.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2652 NO-JIRA: Add "centos" to supported OS ids
  bindata/network/multus/multus.yaml
  bindata/network/openshift-sdn/sdn.yaml
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
Labels: lgtm, approved, jira/valid-reference

#2648 NP-1100: Enable fast ranges
  bindata/network/multus/002-rbac.yaml
  bindata/network/multus/multus.yaml
  pkg/network/multus.go
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, jira/valid-reference
