Repository openshift/cluster-network-operator, pull requests merged in 2025-07, with the labels that each got.

#2731 OCPBUGS-58155: CNO must skip watching IngressController if Ingress capability is disabled in HyperShift
  pkg/controller/ingressconfig/ingressconfig_controller.go
  pkg/controller/ingressconfig/ingressconfig_controller_test.go
  pkg/controller/ingressconfig/mocks_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2735 CORENET-5881: Reconfigure NBDB for route advertisements in LGW
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
Labels: lgtm, approved, jira/valid-reference

#2749 OCPBUGS-59135,OCPBUGS-59134: Annotate whereabouts-controller
  bindata/network/multus/multus.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2734 CORENET-6127: ovn-k: Enable OVN-K feature when PreconfiguredUDNAddresses is enabled
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  bindata/network/ovn-kubernetes/managed/004-config.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
  bindata/network/ovn-kubernetes/self-hosted/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-control-plane.yaml
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
