Repository openshift/cluster-network-operator, pull requests merged in 2025-03, with the labels that each got.

#2653 [Release 4.15] OCPBUGS-51208: Use applyconfigurations for updating network.oprerator status
  pkg/client/client.go
  pkg/client/fake/fake_client.go
  pkg/client/types.go
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_cloudcredential.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_clustercsidriver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_config.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_csisnapshotcontroller.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_etcd.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_ingresscontroller.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_insightsoperator.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubeapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubecontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubescheduler.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubestorageversionmigrator.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_openshiftapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_openshiftcontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_operator_client.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_serviceca.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_servicecatalogapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_storage.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/fake_etcdbackup.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/fake_imagecontentsourcepolicy.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/fake_olm.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/fake_operator_client.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2659 OCPBUGS-52361: frr-k8s: rename validatingwebhook name
  bindata/network/frr-k8s/webhook.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2664 NO-JIRA: ovn-k: sync EgressService with upstream
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved, jira/valid-reference

#2657 OCPBUGS-48305: frr-k8s: align manifests with operator
  bindata/network/frr-k8s/frr-k8s.yaml
  bindata/network/frr-k8s/webhook.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2655 [release-4.17] OCPBUGS-49816: ovn-k, rbac: Enable users read & modify UserDefinedNetwork CRs
  bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml
  bindata/network/ovn-kubernetes/common/009-rbac-udn-editor.yaml
  bindata/network/ovn-kubernetes/common/010-rbac-udn-viewer.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2647 CNTRLPLANE-112: Update managed Azure HCP cloud network config
  bindata/cloud-network-config-controller/managed/controller.yaml
  pkg/network/cloud_network.go
Labels: lgtm, approved, jira/valid-reference

#2651 [Release 4.16] OCPBUGS-50712: Not update status.migration of the network.config CR to empty
  pkg/controller/clusterconfig/migration.go
  pkg/network/cluster_config.go
  pkg/network/cluster_config_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2454 OCPBUGS-52280: Move to use newer IPsec DaemonSets irrespective of MCP state
  bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml
  bindata/network/ovn-kubernetes/common/ipsec-host.yaml
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/platform/platform.go
  pkg/version/semver.go
  pkg/version/semver_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2661 OCPBUGS-52837: frr-k8s: rename validatingwebhook name
  bindata/network/frr-k8s/webhook.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2670 OCPBUGS-5241: Auto opt in for whereabouts-controller
  bindata/network/multus/multus.yaml
  pkg/network/multus_test.go
  pkg/network/network_metrics_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2654 [release-4.17] OCPBUGS-52951: Unexpected Behavior During Cluster Upgrade for the ovn-ipsec-host pods
  bindata/network/ovn-kubernetes/common/80-ipsec-master-extensions.yaml
  bindata/network/ovn-kubernetes/common/80-ipsec-worker-extensions.yaml
  bindata/network/ovn-kubernetes/common/ipsec-containerized.yaml
  bindata/network/ovn-kubernetes/common/ipsec-host.yaml
  pkg/bootstrap/types.go
  pkg/controller/controller.go
  pkg/controller/operconfig/operconfig_controller.go
  pkg/controller/statusmanager/machineconfig_status.go
  pkg/controller/statusmanager/machineconfig_watcher.go
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/names/names.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
  pkg/platform/platform.go
  pkg/util/k8s/ownerref.go
  pkg/util/machineconfig/util.go
  pkg/version/semver.go
  pkg/version/semver_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only
