Repository openshift/cluster-network-operator, pull requests merged in 2025-08, with the labels that each got.

#2759 NO-JIRA: remove PersistentIPsForVirt FG
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-reference

#2755 CORENET-6228: Allow network-node-identity to be enabled for IBMCloud PlatformType
  pkg/platform/platform.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2756 NO-JIRA: Update CNO reviewers/approvers
  OWNERS_ALIASES
Labels: lgtm, approved, jira/valid-reference

#2757 CORENET-6247: Set runAsUser for ovnkube-control-plane
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2740 MGMT-20706: fix DPU host mode support for OVN templates
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
  pkg/network/ovn_kubernetes_dpu_host_test.go
Labels: lgtm, approved, jira/valid-reference

#2752 OCPBUGS-55962: Allow overriding OVN-Kubernetes configuration
  bindata/network/ovn-kubernetes/common/008-script-lib.yaml
  pkg/bootstrap/types.go
  pkg/network/ovn_kubernetes.go
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2769 CORENET-6276: Use priorityClass from HostedControlPlane for OVN and NNI
  bindata/cloud-network-config-controller/managed/controller.yaml
  bindata/network/node-identity/managed/node-identity.yaml
  bindata/network/ovn-kubernetes/managed/ovnkube-control-plane.yaml
  pkg/bootstrap/types.go
  pkg/network/cloud_network.go
  pkg/network/node_identity.go
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2743 CORENET-6130, CORENET-6261, CORENET-6092: Implement PreconfiguredUDNAddresses API changes
  bindata/network/multus-admission-controller/003-webhook.yaml
  bindata/network/ovn-kubernetes/common/001-crd.yaml
  bindata/network/ovn-kubernetes/common/default-net-annotation-policy.yaml
  pkg/network/multus_admission_controller.go
  pkg/network/multus_admission_controller_test.go
  pkg/network/ovn_kubernetes_test.go
  pkg/network/render.go
  pkg/network/render_test.go
Labels: lgtm, approved, ¯\_(ツ)_/¯, jira/valid-reference
