Repository openshift/cluster-network-operator, pull requests merged in 2025-01, with the labels that each got.

#2552 [release-4.16] OCPBUGS-43803: Start feature migration when the cluster CNI is changed to the target type
  pkg/controller/operconfig/operconfig_controller.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2612 OCPBUGS-42609: Disable adding/removing the UDN namespace label
  bindata/network/ovn-kubernetes/common/udn-admission-policy.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2611 SDN-4168: Cleanup ipsec state only when ipsec is not full mode
  bindata/network/ovn-kubernetes/common/80-ipsec-master-extensions.yaml
  bindata/network/ovn-kubernetes/common/80-ipsec-worker-extensions.yaml
  bindata/network/ovn-kubernetes/common/ipsec-host.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2591 SDN-4930: Add host isolation mounts to ovnkube-node
  bindata/network/ovn-kubernetes/managed/ovnkube-node.yaml
  bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2617 OCPBUGS-48323: Pass transit_switch_subnet options in ovnkube-node pod for single-zone
  bindata/network/ovn-kubernetes/managed/common/004-config.yaml
  bindata/network/ovn-kubernetes/self-hosted/common/004-config.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2616 SDN-4930: Fix user-defined-networks-namespace-label binding
  bindata/network/ovn-kubernetes/common/udn-admission-policy.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2621 SDN-5330: Keep IPsec in OVN enabled during the upgrade
  pkg/network/ovn_kubernetes.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2626 [release-4.18] OCPBUGS-48710, SDN-4930: Disable adding/removing the UDN namespace label
  bindata/network/ovn-kubernetes/common/udn-admission-policy.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2623 SDN-5426: (C)UDN CRD: add IPAM section and IPAM.Mode field.
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2610 OCPBUGS-46564: Update egressfirewall CRD to be consistent with ovn-kubernetes repo
  bindata/network/ovn-kubernetes/common/001-crd.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#2627 [release-4.18] OCPBUGS-48443: ovn-k, rbac: Enable users read & modify UserDefinedNetwork CRs
  bindata/network/ovn-kubernetes/common/007-rbac-cluster-reader.yaml
  bindata/network/ovn-kubernetes/common/009-rbac-udn-editor.yaml
  bindata/network/ovn-kubernetes/common/010-rbac-udn-viewer.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2634 OCPBUGS-49667: OVNK should be able to annotate network ID on NADs
  bindata/network/ovn-kubernetes/common/004-rbac-control-plane.yaml
  pkg/network/ovn_kubernetes_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
